### ISSUE TITLE
User babeljs as a transpiler.

### ISSUE THREAD

**Issue by nishp1** [ozone-development/ozp-center#104]

**Comment by nishp1** [comment]
@mparizernc Done on `babeljs` branch in center.

**Comment by mparizernc** [comment]
@nishp1 Need a little more info like what is it and what am I supposed to be testing with it?

**Comment by nishp1** [comment]
We are using to convert ES6 code ES5. Just needs a smoke test.

**Comment by mparizernc** [comment]
* The Calendar and Time controls for Notifications do not work.
 Uncaught ReferenceError: popoverContainer is not definedmain.js:71 React.createClass.componentWillMountmain.js:33 (anonymous function)main.js:62 v.Mixin._mountChildByNameAtIndexmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:33 (anonymous function)main.js:33 R._performComponentUpdatemain.js:33 R.performUpdateIfNecessarymain.js:33 amain.js:41 r.performmain.js:41 r.performmain.js:33 h.performmain.js:33 (anonymous function)main.js:41 r.closeAllmain.js:41 r.performmain.js:78 p.batchedUpdatesmain.js:33 omain.js:78 g.dispatchEvent

 Uncaught ReferenceError: popoverContainer is not definedmain.js:71 React.createClass.componentWillMountmain.js:33 (anonymous function)main.js:62 v.Mixin._mountChildByNameAtIndexmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:33 (anonymous function)main.js:33 R._performComponentUpdatemain.js:33 R.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:33 R.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:33 (anonymous function)main.js:33 R._performComponentUpdatemain.js:33 R.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:33 R.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:33 (anonymous function)main.js:33 R._performComponentUpdatemain.js:33 R.performUpdateIfNecessarymain.js:33 amain.js:41 r.performmain.js:41 r.performmain.js:33 h.performmain.js:33 (anonymous function)main.js:41 r.closeAllmain.js:41 r.performmain.js:78 p.batchedUpdatesmain.js:33 omain.js:78 g.dispatchEvent

**Comment by nishp1** [comment]
@mparizernc pushed a fix

**Comment by nishp1** [comment]
Merged into temp-master.

**Comment by mparizernc** [comment]
Verified that the issues with the calendar and time controls have been resolved.
