### ISSUE TITLE
Categories are broken when editing a listing

### ISSUE THREAD

**Issue by rpokorny** [ozone-development/ozp-center#117]
Steps to reproduce
1. Start with a fresh database
2. load the sample data
3. Edit Chart Course

4. Observe the Categories field in the form
Expected Result: "Business" and "Tools" categories are displayed
Actual result: No categories are displayed

5. Attempt to add a category using the drop down on the Category field
Expected Result: The category that you click on is added
Actual Result:  When you click, "Business" and "Tools" appear as selected categories in addition to a new category that is not always the one you selected.  It is often the next one alphabetically, as if "Business" was removed from the selectable list right as you click, changing which row falls under your mouse.

**Comment by nishp1** [comment]
Which branch?

On Wed, Mar 4, 2015 at 3:32 PM, rpokorny <notifications@github.com> wrote:

> Steps to reproduce
> 1. Start with a fresh database
> 2. load the sample data
> 3. Edit Chart Course
>
>    1.
>
>    Observe the Categories field in the form
>    Expected Result: "Business" and "Tools" categories are displayed
>    Actual result: No categories are displayed
>    2.
>
>    Attempt to add a category using the drop down on the Category field
>    Expected Result: The category that you click on is added
>    Actual Result: When you click, "Business" and "Tools" appear as
>    selected categories in addition to a new category that is not always the
>    one you selected. It is often the next one alphabetically, as if "Business"
>    was removed from the selectable list right as you click, changing which row
>    falls under your mouse.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/center-ui/issues/117>.
>



-- 
Nish

**Comment by mparizernc** [comment]
All Browsers

Verified that the categories now show up as expected.
