### ISSUE TITLE
create/edit confirm box interacts poorly with the Back button

### ISSUE THREAD

**Issue by rpokorny** [ozone-development/ozp-center#118]
Browser: Chrome

Steps to Reproduce

1. navigate through the UI to the create/edit page for an existing listing
2. make a change to the listing but do not save
3. Click the browser's Back button
4. On the confirmation box, click cancel
Expected result: the confirmation box goes away and you are still on the create/edit page, able to continue using it
Actual Result: the confirmation box reappears repeatedly (if you keep clicking cancel).  Each time it appears the URL in the address bar goes back another step in the tab's history, until you get to the beginning and the page is replaced with the New Tab screen.

@nishp1 has suggested that the following code might work:

```
window.confirm(CreateEditPage.UNSAVED_MESSAGE) ?
                    CreateEditActions.discard() :
                    transition.redirect(component.getPath(), component.getParams(), component.getQuery());
```

**Comment by nishp1** [comment]
Pushed to temp-master.

**Comment by mparizernc** [comment]
All Browsers

Verified that the back button when cancel is hit leaves the route alone and it works as expected.
