### ISSUE TITLE
IE9 does not support window.console EXCEPT when Developer tools are active

### ISSUE THREAD

**Issue by CJOchs** [ozone-development/ozp-center#122]
The center-ui javascript uses console.{log,warn} to provide an activity trail.  Unfortunately IE9 and earlier do not define a window.console object unless you are using the developer tools.

We will need to update the javascript/html files to handle this case.

**Comment by CJOchs** [comment]
Note: this was verified on the high side by checking for and defining window.console in the index.html file:

```javascript
<script>
    if (!window.console){ 
        var console = {log: function(){},
                               warn: function(){}};
   }
</script>
```

**Comment by stephanieerin** [comment]
Why was this reopened? Has this not been handled by the code push last week?

**Comment by mparizernc** [comment]
Talked with CJ and this can be closed.
