### ISSUE TITLE
Document configuration steps

### ISSUE THREAD

**Issue by brian428** [ozone-development/ozp-center#123]
Apologies if this isn't the best place to ask about this, but the StackOverflow site isn't active yet and the lists all seem to still be covering OWF. If there's a better place for future questions like this, please let me know.

After some initial trouble (which will probably result in creating some additional Github issues), I got the center-ui app up and running. However, when I browse to the app, the first thing I get is a request to present a certificate. I can't find anything in the docs about the security setup, and even searching the Github repo for words like "config", "auth", "pki", or "security" don't reveal anything relevant.

Is this the expected default behavior? Is there a trick to setting up the app to allow automatic admin login? Or better yet, is that a document or page somewhere that I've missed that explains how center-ui is actually configured?

**Comment by mparizernc** [comment]
This project is still in development as is documentation which at this point is incomplete.  Once this project has set a formal release a full set of documentation will be delivered with the product.  If you have additional question about the legacy versions of the product you can view the github pages for the Ozone Widget Framework by going to http://ozone-development.github.io/ozone-website/owf.html, additional questions for those products can be posted to ozoneplatform-users group on google groups.  I do want to extend our appreciation for your interest in our project.

**Comment by brian428** [comment]
Thanks. However, I don't need information on the legacy OWF, as we're already using it within a gov't agency on a large project. But we know that our project is going to migrate to OZP when it is released, and we need to get some idea of what's going to be involved in that migration. 

I understand that docs will be coming, but right now I can't even figure out how center-ui is configured. Are any of the OZP dev team watching the existing mailing lists to answer OZP-related questions? Is there a new list somewhere that I'm not aware of? 

Or, if everything is internal/private right now, could someone create a quick and dirty document on OZP and center-ui configuration, which simply points to some source files or other repositories that I can look at? I don't have a problem doing most of the work myself, but right now I simply have no idea where to even start looking.

**Comment by rpokorny** [comment]
Here is a very quick intro:  The new application is split into multiple projects.  There is a single backend project (ozp-rest) and several frontend projects (mainly center-ui, hud-ui, and webtop-ui).  In order to play around with things you will need at least ozp-rest and whichever of the frontends you are interested in.  

The backend is a grails project.  You can start it in dev mode by running `grails run-app -https` (you'll need to have grails 2.3.7).  You can build the war by running `grails war`.  That war file can then be dropped into an Apache Tomcat or other servlet container, but without a few supporting config files it won't run properly.  Those config files are much the same as what was required by 7.x, if you are familiar with that.  

On the frontend, center-ui and hud-ui are both setup similarly, but webtop-ui is a bit different.  I am personally not as familiar with webtop-ui, but for the other two you can run them in dev mode using `npm start` and you can build them (producing a `dist` directory) using `npm run build`.  Each frontend project connects to the others and the backend via a configurable set of URLs in `dist/OzoneConfig.js` (a generated file).  These URLs can be customized either by editing that file or by setting environment variables when running the start or build commands.  

By default, center-ui looks for the backend at https://localhost:8443/marketplace , so any cert prompts that you are getting are probably the result of whatever server you have running on that port, not a result of anything in center-ui

**Comment by brian428** [comment]
Hmm, interesting, because I'm not running any server yet (unless center-ui sets up some sort of internal server, or defaults into some sort of mock data mode). But this helps, at gives me a place to start by looking at ozp-rest. Thanks.

**Comment by rpokorny** [comment]
It does not set up anything like that.  Speaking of sample data, you can load some by running `npm run loadSampleData` in ozp-rest

**Comment by brian428** [comment]
Yep, I got that far but ran into the fact that node-gyp requires Python to be installed, as well as (apparently) Visual Studio C++. If that's intended, it might be worth adding that to the ozp-rest readme?

**Comment by arw180** [comment]
As a developer on OZP, I've created a vagrant setup to make this process a little easier. It's definitely a work in progress, but I've tried to document everything in the README (and in the provisioning scripts) as best I can. https://github.com/ozone-development/vagrant-configs/tree/master/build-and-deploy

Even if you don't want to use vagrant, the provisioning scripts in there should provide fairly good detailed instructions on what is required to get a system up and running (on Ubuntu 14.04, anyway). Note that this setup is more complicated than you might need, as it uses an actual MySQL database (vs the in-memory H2 database that is used automatically by the ozp-rest app when run in development mode) as well as a standalone elasticsearch instance (again as opposed to an in-memory one). 

I'd like to create additional vagrant setups that are much simpler for times when all this additional complexity isn't required, but it hasn't made it to the top of my priority queue yet, unfortunately.

**Comment by brian428** [comment]
Thanks, I'll take a look at that! Just as a general note, I can tell you that at least several large existing projects within the gov't that use OWF are starting to look at what it will take to migrate to OZP. So I would expect that noob questions like mine are probably going to get increasingly frequent. 

I understand that things are still in progress, and believe me, I know developers don't enjoy writing documentation. That said, I think it would be a good idea to try and set a small amount of time aside to whip up something current. Even if it's just a quick-and-dirty "brain dump" that someone writes in an hour or two, that would help immensely to bridge the gap until more refined docs can be created. 

Like I said, I'm willing to try and figure out the details on my own, but right now I really wouldn't have had any idea where to even start. If I hadn't asked, I'd have had a tough time figuring out that I should start by looking at center-ui, or ozp-rest, or what the vagrant repo was for, and so on. So while I don't expect you to hold our hands through everything, I would ask you to consider throwing something out there to ask as a starting point. Even if it is incomplete or "raw". It'll probably save you some time answering OZP noobs like me going forward. :-)

Anyway, thanks again!

**Comment by arw180** [comment]
First, it's great to hear people outside of the dev team are starting to get their hands dirty with OZP, so thank you for the questions! I wish I could tell you that "How do I set up a local OZP environment" is a noob question, but alas, it's something that even the developers occasionally struggle with, especially if you want to be able to test with IE9.

What is your primary goal in setting up this local environment? Are you most interested in it from an OZP application developer's perspective, or seeing how Center looks/works and what information is required to migrate existing applications from OWF to OZP? Or perhaps something else entirely?

I am in vehement agreement that we need documentation (and ideally scripts) on how to set up a complete local OZP environment for a couple different scenarios, and I will do my best to move that towards the top of the priority queue, even if the first draft is a bit rough around the edges.

**Comment by brian428** [comment]
Just to answer your question: I'm interested in both (building new apps, and migrating existing OWF apps).

**Comment by tonyalletag** [comment]
Documentation Links:

General Documentation:
https://github.com/ozone-development/ozp-documentation
http://ozone-development.github.io/ozone-website/
https://github.com/ozone-development/ozp-documentation/wiki
https://github.com/ozone-development/ozp-documentation/tree/master/Documentation

IWC Documentation:
http://ozone-development.github.io/ozp-iwc/ http://ozone-development.github.io/ozp-iwc/FAQ.html

OZP Release Info:
https://github.com/ozoneplatform/ozp-releases

OZP Backend (In Development - not in production)
https://github.com/ozone-development/ozp-backend
