### ISSUE TITLE
Create/Edit page - Typing into any field causes the page to scroll up to the top

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#125]
I started typing into the resources field on the Create/Edit page and every time I typed a character the window would scroll up to the top of the page. This is happening with any form on the page. I am on the temp-master branch.

**Comment by sdeighan** [comment]
Unfortunately, fixing this seems to have compromised two other features that were implemented, so we will need them back.
1. In the navigation tabs, clicking on a field label name should scroll the page to that field.
2. As you scroll down the page, the tabs need to reflect where you are. The correct tab should open/be open while you are in a particular area unless you override that by opening another tab and clicking a field name

**Comment by wski** [comment]
I don't think the features ever worked, I think it just appeared that way because every time the React component updated it scrolled to the top. Num. 2 may have but the code that was removed couldn't have been doing that. Let's open new issues for the following two concerns

**Comment by wski** [comment]
I do see the part for part 2 of your response was broken by the fix-- I'll patch that back in now

**Comment by sdeighan** [comment]
I would be glad to open another issue for the following and opening. However, the first part always worked and is very broken. Without being able to click on a field name, there is no point in having the navigation tabs at all.

**Comment by rpokorny** [comment]
As the person who implemented the nav sidebar, I'm fairly certain it never did number 2 but definitely did do number 1 (which is the whole point of the sidebar).

**Comment by wski** [comment]
Alright, I'll go have a look at it-- I'll try to re implement what was there; for some reason everything the block of code was looking for seems to have become undefined which is what was probably causing this issue to start

**Comment by rpokorny** [comment]
This bug also did not exist when this was first implemented, I assume it was introduced since then.

**Comment by sdeighan** [comment]
The tab following has been moved to Issue #155

**Comment by wski** [comment]
Fixed, Just needed the refs added to getDOMNode on the previous code to get the click functionality back. I'm guessing something changed with layout and it just needed the reference fixed
