### ISSUE TITLE
Detailed View - Adding a Contact causes the Resources tab to not show

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#130]
I added a contact to a listing and then saved.  I then opened the Detail View and went to the Resources tab and the resources tab would not open the following error was thrown in the console:

```Uncaught TypeError: Cannot read property 'name' of undefinedmain.js:69 (anonymous function)main.js:69 i.createClass.renderTechSuppotmain.js:69 i.createClass.rendermain.js:33 (anonymous function)main.js:33 (anonymous function)main.js:62 v.Mixin.mountChildrenmain.js:62 s.Mixin._createContentMarkupmain.js:62 (anonymous function)main.js:62 v.Mixin.mountChildrenmain.js:62 s.Mixin._createContentMarkupmain.js:62 (anonymous function)main.js:62 v.Mixin._mountChildByNameAtIndexmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:62 v.Mixin._updateChildrenmain.js:62 v.Mixin.updateChildrenmain.js:62 s.Mixin._updateDOMChildrenmain.js:62 (anonymous function)main.js:40 f.Mixin.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:62 s.Mixin.receiveComponentmain.js:33 (anonymous function)main.js:33 P._performComponentUpdatemain.js:33 P.performUpdateIfNecessarymain.js:40 f.Mixin.receiveComponentmain.js:33 P.receiveComponentmain.js:33 (anonymous function)main.js:33 P._performComponentUpdatemain.js:33 P.performUpdateIfNecessarymain.js:33 amain.js:41 r.performmain.js:41 r.performmain.js:33 h.performmain.js:33 (anonymous function)main.js:41 r.closeAllmain.js:41 r.performmain.js:78 p.batchedUpdatesmain.js:33 lmain.js:33 P.replaceStatemain.js:33 P.setStatemain.js:69 i.createClass.onShownmain.js:39 (anonymous function)main.js:31 it.fn.extend.on.imain.js:31 it.event.dispatchmain.js:30 it.event.add.g.handlemain.js:31 it.event.triggermain.js:31 (anonymous function)main.js:20 it.extend.eachmain.js:20 it.fn.it.eachmain.js:31 it.fn.extend.triggermain.js:56 (anonymous function)main.js:31 it.fn.extend.on.imain.js:56 e.support.transition.e.event.special.bsTransitionEnd.handlemain.js:31 it.event.dispatchmain.js:30 it.event.add.g.handlemain.js:31 it.event.triggermain.js:31 (anonymous function)main.js:20 it.extend.eachmain.js:20 it.fn.it.eachmain.js:31 it.fn.extend.triggermain.js:56 e.fn.emulateTransitionEnd.r```

**Comment by hoganmaps** [comment]
issue is in temp-master branch, not master branch.

will check again when develop is ready to use.

**Comment by mparizernc** [comment]
I was unable to reproduce the issue in the develop branch so closing this issue.
