### ISSUE TITLE
Create/Edit Page - Screenshots Field

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#136]
# Re-styling the Screenshots field
Re-styling the screenshots field in the Create / Edit page in order to reduce confusion when trying to upload a screenshot. During testing, the existing styling was found to be confusing and this update should clarify the interactions

## Included
1. Moving the "Preview" and "Full-Size" fields side by side
2. Adding numbering for each screenshot row
3. Creating a smaller preview-image function with width to match the length of the browse-for-image input. Height remains in the same proportion to the width as it was in full size (600px x 376px)
4. If not done already, moving the preview-image functions below the input fields
5. Renaming the "Add" button to "Add Additional Screenshot"
6. Moving the "Add Additional Screenshot" button to be left-aligned with the row numbers
7. Ensuring that whole screenshot field errors appear below the main label and that sub-field specific errors appear near the sub-field that needs the user's attention

### Initial State / Empty
![mp_createeditform_screenshots01](https://cloud.githubusercontent.com/assets/7987446/6714444/ac250688-cd6e-11e4-9b9d-fbb15c710b56.png)
### Filled inputs
![mp_createeditform_screenshots02](https://cloud.githubusercontent.com/assets/7987446/6714443/ac23f93c-cd6e-11e4-97a8-f5cb0700748f.png)
### First row filled, new screenshot added
![mp_createeditform_screenshots03](https://cloud.githubusercontent.com/assets/7987446/6714442/ac233d76-cd6e-11e4-8a1f-9ba425e959a8.png)
### Error, whole field
![mp_createeditform_screenshots_error01](https://cloud.githubusercontent.com/assets/7987446/6714450/b20049a0-cd6e-11e4-9698-f288965100a7.png)
### Error, sub-field
![mp_createeditform_screenshots_error02](https://cloud.githubusercontent.com/assets/7987446/6714451/b2018432-cd6e-11e4-802a-30f11b406ba6.png)

**Comment by mparizernc** [comment]
All Browsers

I have tested the screenshots and resources and have put tickets in for the issues found moving this over to test in prod.

**Comment by sdeighan** [comment]
As a note: The button label has been modified from "Add New Screenshot" to "Add New" to reduce the complexity of the restyling update.

If additional clarification is required for users, we will add a new ticket focusing on the button label becoming more specific to each field that it relates to (e.g. "Add new screenshot", "Add new resource", "Add new contact", etc.)
