### ISSUE TITLE
Update main page to show user's newly submitted rating

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#145]
1. On the main center page click an app.
2. In the modal created, rate the app.
3. Close the modal.
4. The rating is not reflected on the main display until the user refreshes the page.

Would like to get rid of the need to refresh the page before the rating is displayed.

**Comment by clarkjefcoat** [comment]
I realize that the only way a user would notice is if the app didn't have any (or very few) rating to begin with.  In our testing that is what we had.  At this point this issue management visible and has made our testers unsure of whether their rating were accepted.

**Comment by mparizernc** [comment]
This works on the Discovery page however if someone has done a search changes are not reflected on the search page.


Steps:

1) Do a search for term i.e. "air"
2) Open the Detail View and rate a listing
3) Close the Detail View
4) The rating is not reflected on the Search page

**Comment by wski** [comment]
Split into new bug

**Comment by wski** [comment]
Split into new bug #168
