### ISSUE TITLE
Search & Discovery - Show a specific message if search returns no results

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#147]
1.  Select some combination of categories, types, and agencies that results in no matches.
2.  The main portion of the screen is blank (indicating no search results).

The blank screen is confusing to users.  Suggest adding at a minimum a message that says "No search results returned".  Or if possible a message that reflects their search - something like "Your search for ZZZ and XXX did not return any results".

**Comment by mparizernc** [comment]
All Browsers

I verified that the No Results messages appears when the filters are selected with no results and when a search term has no results.
