### ISSUE TITLE
Search & Discovery - Launching an app brings you to the 'submit a listing' page

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#148]
1. Go to AppsMall center
2. Select an app and hover over it. Select the small launch button next to the bookmark button. The 'submit a listing' page will open up in a new browser tab.

**Comment by mparizernc** [comment]
Is it possible that the launch URL is the submit a listing page.  Someone may have just copied that URL since they were on that page?

**Comment by clarkjefcoat** [comment]
I can confirm that in this example the launch URL is the submit a listing page.  I agree that this looks confusing, however it is the correct behavior.
