### ISSUE TITLE
Create/Edit - Form not resetting when accessing create/edit from Global Toolbar

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#151]
To recreate issue Edit a listing in Listing management then click submit a listing from the dropdown menu

**Comment by mparizernc** [comment]
What happens is data from the previous listing is carried forward to the new form.  Make sure when looking at fixing this bug to look at the URL to make sure it is a new listing.

**Comment by wski** [comment]
I was thinking that when yo create a new listing the data should always be wiped from that form--I figured that's the point of the draft.

**Comment by mparizernc** [comment]
Correct, I just wasn't sure if it was leaving the id for the original listing in the URL.  You are right though it should be  a brand new listings with the only thing populated being the owner (who ever is logged in).

**Comment by wski** [comment]
There is an issue with error checking when the page is loaded but I think it will be fixed in #220

**Comment by wski** [comment]
Talked with @clarkjefcoat and came to a decision to put the partial fix that is in now (It resets the form when coming from editing another form) but there a few remaining issues with validation etc. I've opened a new issue (#246) to fix the remaining issues or come up with a more suitable fix post IOB

**Comment by hoganmaps** [comment]
it appears that when you go to edit a listing, and then submit a new listing, several of the fields are still carried over to the new form... unfixed!

**Comment by kgordon-1** [comment]
Passed – Tested in STG
Verified fixed by modifying a listing.  Then open the page to submit a listing.  All fields were blank except Owners which is always populated with the user’s information.
