### ISSUE TITLE
Listing Management - The filters in Firefox and IE are shown incorrectly when some are selected

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#152]
Go to Listing Management >  My Listings and select Needs Action or Draft and the filters look like the screenshot below. This was an old bug that had been fixed in temp-master but it is back. It happens on all of the Listing pages

![uploads/2a08151e-cb61-4a45-b5c1-357a4acd7e71/3-24-2015 1-18-32 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2a08151e-cb61-4a45-b5c1-357a4acd7e71%2F3-24-2015+1-18-32+PM.png)

**Comment by clarkjefcoat** [comment]
From today's v0.7.3-rc center this is still a bug.  Looks fine in Chrome, but in IE and Firefox it looks like:

![image](https://cloud.githubusercontent.com/assets/7015118/7033011/dc6c8d26-dd44-11e4-9e60-5a4e5afd9a84.png)

Above screenshot is from Firefox 24 running on Ubuntu 14.02.  IE9 running in a Windows 7 VM looks similar.

**Comment by clarkjefcoat** [comment]
Things look bad if the results for the "State" that you selected fill less than 1 full row.

**Comment by mparizernc** [comment]
All Browsers

Verified that the filters are not shifting anymore. I looked at the My Listings and the All Listings pages.  I tried with less then a full row or listings and more then a single row of listings. This is ready to be tested in Prod.
