### ISSUE TITLE
Search and Discovery - IE the search box is misaligned 

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#153]
The Search bar is misaligned see screenshot.  This was fixed in temp-master but is broken in develop.
![uploads/4ba6a25d-9f9d-4e0b-bec2-b4f2d6ecefc5/3-24-2015 1-32-42 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4ba6a25d-9f9d-4e0b-bec2-b4f2d6ecefc5%2F3-24-2015+1-32-42+PM.png)

**Comment by sdeighan** [comment]
I fixed this before, there should be a record of it in this issue: Search and Discovery Page - The Search bar is shifted down when using in IE #120

**Comment by mparizernc** [comment]
All Browsers 

Verified that it is fixed once again.
