### ISSUE TITLE
Create/Edit Page - Required listing type missing error message

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#157]
1.  Fill in the Title
2.  Fill in the Short Description
3.  Press Save

The page does not save, it scrolls to the Listing Type field (which is required), but does not display an error message.  If Listing Type is required to save a draft please include an error message.

**Comment by hoganmaps** [comment]
but exists now in edit an existing widget

**Comment by clarkjefcoat** [comment]
Has an intervening fix broken this again?  I don't see an error message.

![missingerrormessage](https://cloud.githubusercontent.com/assets/7015118/7985456/e4b1a840-0a9e-11e5-9259-57e5ec46d614.png)

**Comment by hoganmaps** [comment]
this is part of a larger issue. whatever the bug is affects multiple required input fields. The tags validation still works for whatever is input

**Comment by hoganmaps** [comment]
Current fix: When a user types in the title, if 'type' is not selected, an error message pops up. The draft can be saved once the title and type are filled in
![uploads/318cafcd-978b-48ce-80e2-0db540e86faf/Screen Shot 2015-06-08 at 2.18.50 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F318cafcd-978b-48ce-80e2-0db540e86faf%2FScreen+Shot+2015-06-08+at+2.18.50+PM.png)

**Comment by wski** [comment]
Confirmed that this is working, but we should revisit at a later date why the error messages for the first two items are a different color than that of the rest. 
http://gyazo.com/5a1540f85294127b01183e32f584b99c

**Comment by kgordon-1** [comment]
Passed -- Tested on STG
In Submit Listing, enter data in the name field only and clicked save.  The Listing Type field is highlighted in a red box.  Red bar is displayed over field with the message “One category is required.” Plus a pop up box with a big red X and the message Could not save!.  All indicate that the user is unable to save and there is enough indication as to why.
