### ISSUE TITLE
Search & Discovery: Add search parameter details on results page

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#161]
Add the criteria currently affecting the search at the top of the results page and include a "Reset" button

**Comment by sdeighan** [comment]
![mp_searchanddiscovery_searchresults](https://cloud.githubusercontent.com/assets/7987446/7145665/f772e666-e2bb-11e4-80c0-820874192ecb.png)

**Comment by wski** [comment]
I have removed the 'x' buttons per @arw180's suggestion, there may need to be future discussion on this but they should not be expected to appear for the tests.

**Comment by arw180** [comment]
I looked at this a bit with @wski the other day. I like the display of search criteria with labels, along with the ability to share search urls, but adding duplicate functionality that allows users to modify their search from these labels is not something I think we should be doing (i.e. the `x` button on labels). I'm not opposed to the `Clear All` button, since (I imagine) that would just redirect the user to the main Discovery page.

**Comment by blaino** [comment]
@wski, while testing on ci-develop.amlng.di2e.net noticed that entering "mail tool" in the search input text area yields a single label called "mail tool" and not two labels called "mail" and "tool" respectively. The spec above has two separate labels. 
![uploads/b5cc0407-6b5b-441a-9e13-486e4567c0af/Screen Shot 2015-07-08 at 8.36.02 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb5cc0407-6b5b-441a-9e13-486e4567c0af%2FScreen+Shot+2015-07-08+at+8.36.02+AM.png)

**Comment by mparizernc** [comment]
@wski, if you have to many parameters it messes up the formatting of the page.
![7-9-2015 8-50-10 am](https://cloud.githubusercontent.com/assets/7975509/8595649/e5132ff4-2617-11e5-99e9-44046616dbc3.png)

**Comment by wski** [comment]
This will probably lead into our issues with responsive design but I'll patch it as best I can, though I think this bug is a part of a larger undertaking that needs to be done.

**Comment by blaino** [comment]
Tested on all four browsers. The issue that @mparizernc found seems to be resolved. 
<img width="1383" alt="screen shot 2015-07-10 at 8 40 26 am" src="https://cloud.githubusercontent.com/assets/1998900/8618813/91186de2-26df-11e5-8a5d-d9a2adc4c5b4.png">

**Comment by mparizernc** [comment]
Verified that parameters in all browsers on staging.

**Comment by blaino** [comment]
Retroactive :+1:
