### ISSUE TITLE
Listing Management - The scroll bar moves from the right side of the browser to the right side of the content after editing a listing

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#167]
Develop Branch

I noticed that when I went to the listing management pages that there were 4 columns of listings. I then went to edit a listing and went back to the Listing Management pages and there was only 3 columns. After further investigation I found that the scroll bar initially is at the right side of the browser. After coming back from editing a listing the scroll bar moved from the right side of the browser to the right side of the content causing less usable space causing the reducing of the columns.  (Content means where the white background and gray background meet.)

**Comment by rpokorny** [comment]
I think I know what's causing this.  The create/edit page is styled such that the page overall never scrolls - only the form in the middle does.  The only way that I could cause this behavior was to add (when create/edit is opened) a css class to one of the very high-level elements (like `html` or `body`) that changes their sizing.  This class is probably not being removed appropriately when the create/edit page is closed.

**Comment by hoganmaps** [comment]
I can't seem to replicate the 4 to 3 column issue with the latest chrome or FF24, but i see the scroll bar part

**Comment by mparizernc** [comment]
Interesting I was able to reproduce it on every browser. But I assume fixing the scroll bar should fix the column issue I was seeing.

**Comment by hoganmaps** [comment]
Just made a change that should fix the scrollbars on develop

**Comment by mparizernc** [comment]
All Browsers

Verified that the scroll bar no longer moves.

**Comment by jloveland18** [comment]
All Browsers.
Verified that when I went to the listing management pages there were 4 columns of listings. I then went to edit a listing and went back to the Listing Management pages and there were still four columns.
