### ISSUE TITLE
Errors - Error page does not display when going directly to a specific route

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#169]

**Comment by mparizernc** [comment]
Can you please give a bit more detail on what you did and what happened, please?

**Comment by wski** [comment]
For instance load center with an improper back end url and go to http://localhost:8000/dist/#/edit you will just get a white page instead of the error page.

**Comment by sdeighan** [comment]
Well, I think the errors are in the back end - If I'm not mistaken, this may be a very large effort (Someone like @rpokorny would actually know, though).

In the actual instance of OZP, does this have the potential to be a fairly common problem for the backend to be going to the wrong URL? Or is this primarily an issue for us as developers of OZP?

**Comment by rpokorny** [comment]
By the error page, you mean the full-page thing that says the HTTP status code and any error message that it can find?

Getting that to show up in this case shouldn't be too hard.  It wouldn't require backend changes as @sdeighan thought.

**Comment by wski** [comment]
It's not a backend thing, It just needs to listen for errors and report
them from all routes in center is all. Not sure how off hand but it
shouldn't be that hard.

On Thu, Apr 9, 2015 at 12:48 PM, Sarah Deighan <notifications@github.com>
wrote:

> Well, I think the errors are in the back end - If I'm not mistaken, this
> may be a very large effort (Someone like @rpokorny
> <https://github.com/rpokorny> would actually know, though).
>
> In the actual instance of OZP, does this have the potential to be a fairly
> common problem for the backend to be going to the wrong URL? Or is this
> primarily an issue for us as developers of OZP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/169#issuecomment-91288469>
> .
>



-- 
Matt Wisniewski \ *Software Engineer *

Website and Application Development
tel (443) 653-0303
contact.mattdylan@gmail.com \ http://32dev.com <https://32dev.com>
<http://www.8bit.ws/>

**Comment by sdeighan** [comment]
I'm glad that I'm mistaken; this is why I call in the cavalry. ^_^

**Comment by tonyalletag** [comment]
@wski - Can you update this ticket, should it be closed?

**Comment by wski** [comment]
I think it can be closed. I do not believe the issue was ever resolved however our home page does not show errors in some instances (such as the backend URL being incorrect, or being unauthorized). I think we should address these issues when the `ozp-backend` is fully implemented to avoid doing the same work twice.
