### ISSUE TITLE
New listing "NewSpace" image is not displayed in HUD

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#172]
I created a new listing called NewSpace, and had Jen to publish it.  I located the listing in center and bookmarked it.  The image in HUD is not displayed, it has a white line boarder with no image, however the image is displayed in Center/shopping bag.

Clark may have fixed this.

**Comment by kgordon-1** [comment]
Also, the image is not displayed in WebTop/dashboard.  The select box displays a white outline and when selected to display on dashboard, the name is display but not image.  I have the image on high side.

**Comment by clarkjefcoat** [comment]
Discussion of the cause of this issue in #176.

**Comment by clarkjefcoat** [comment]
Fixed app launch url in database to solve user's immediate problem.  Opened ticket #176 to document root cause.
