### ISSUE TITLE
Horizontal scroll bar on listing, not displayed.  

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#173]
In WebTop, re size listing to end on screen or as far over as I can.  The re size worked but the edge was hidden behind the screen edge making it difficult to see. The bottom scroll bar did not displayed which would allow the image to be moved over.  Picture is with KarenG and Clark on high side.

**Comment by clarkjefcoat** [comment]
This issue was moved to ozone-development/ozp-webtop#512
