### ISSUE TITLE
Location lister, unable to save and no error message displayed

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#174]
bookmark the location lister and display it in WebTop/dashboard.
Click on Add Location
Enter Title
In Latitude field enter -50 (it should look like this 0-50)
In Longitude field enter 30 
Note, the Save button is grayed out.  
It will not allow you to save because of the 0-50 and it does not display an error message as to what is the problem.  

Also, both fields have the same problem.

**Comment by clarkjefcoat** [comment]
This issue was moved to ozone-development/ozp-demo#24
