### ISSUE TITLE
Listing URLs that contain spaces cause problems

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#176]
_From @clarkjefcoat on April 6, 2015 17:37_

If an approved listing has spaces in its launch URL:
1. it will not launch correctly in Webtop
2. if added to the HUD it cannot be deleted

Suggest that we change spaces to %20 before saving to the database.

I have tested this with spaces in the query parameters.

_Copied from original issue: ozone-development/ozp-rest#56_

**Comment by rpokorny** [comment]
I would recommend, rather than automatically changing what the user has entered before saving it to the DB, that we improve the validation of URL fields so that spaces and other invalid characters do not validate and the user is forced to correct them.
