### ISSUE TITLE
Search & Discovery - Categories menu needs label

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#178]
The label “Categories” is missing from the list of categories.

**Comment by sdeighan** [comment]
This was intentional - since the other two filter criteria sets (Listing Types and Organizations) were removed, Categories are the only items over there. We felt keeping the Categories label was a little redundant.

**Comment by tonyalletag** [comment]
We have some feedback from users/tester that this is causing some confusion.  Lets not do anything yet until we get additional feedback.

**Comment by kgordon-1** [comment]
Throughout the system (list management)  you have the 3 heading listed.
Now you have a group of things on the left panel with no heading.  First
time user will want to know what are they.

**Comment by sdeighan** [comment]
In Listing Management, there is more than one type of content in the left sidebar filters. Usually at least 3 kinds of filters. Generally, if there's no other items in an area and all the categories are displayed, an explicit visual label for the filters, especially one as common and industry standard as "Categories", is not provided. But if you have concerns or are seeing confusion, we can certainly add one in. It shouldn't take us long at all. @tonyalletag , please let us know if /when we should act on this.

**Comment by mparizernc** [comment]
All Browsers

Verified the Categories label is there and that the Home link has been made specific to be marketplace Home.  Ready to be tested in Prod.
