### ISSUE TITLE
Feature - Add "Private" & "Public" Listings Functionality

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#182]
Organization need to have the option to list an app as private. Only users within that apps organization shall be able to search and view a private app.

AppsMall Admin need to be able to see all private apps.

**Comment by sdeighan** [comment]
![mp_detailedview_admin_mpsteward_pendingaml](https://cloud.githubusercontent.com/assets/7987446/7089055/e9c48cb6-df4d-11e4-8903-155dc4f7bb9d.png)
![mp_detailedview_admin_mpsteward_pendingorg](https://cloud.githubusercontent.com/assets/7987446/7089056/e9c751bc-df4d-11e4-9462-e0c1427fec8a.png)
![mp_detailedview_admin_mpsteward_privatepending](https://cloud.githubusercontent.com/assets/7987446/7089057/e9ce2b04-df4d-11e4-8113-d770d6d549af.png)
![mp_detailedview_admin_mpsteward_published](https://cloud.githubusercontent.com/assets/7987446/7089059/e9cff9d4-df4d-11e4-94c9-be3ccc5d37af.png)
![mp_detailedview_admin_orgsteward_privatepending](https://cloud.githubusercontent.com/assets/7987446/7089058/e9cfb00a-df4d-11e4-8f6c-a3951a591924.png)
![mp_detailedview_admin_owner_privatepending](https://cloud.githubusercontent.com/assets/7987446/7089060/e9d4cfcc-df4d-11e4-86d1-20e3e40a6729.png)
![mp_detailedview_admin_owner_privaterequest](https://cloud.githubusercontent.com/assets/7987446/7089061/e9dcfe86-df4d-11e4-9f5e-51e492acf286.png)

**Comment by tonyalletag** [comment]
Dependent on new backend

**Comment by bhalt** [comment]
@tonyalletag looks like the original requirement/mockups was for both the Org Steward and Center Steward to individually approve/deny a private request. Is this still accurate, or should the public/private status be chosen by the App Creator, much like the "enabled" status?

Keeping @blaino in the loop. 

(https://github.com/ozone-development/ozp-documentation/wiki/Private-Listings)

**Comment by blaino** [comment]
And, the original plan includes a "short justification" for why the listing should be private. Are we still doing that?

**Comment by tonyalletag** [comment]
The App Create should have the option to select a "private" status for the application when it is submitted

**Comment by bhalt** [comment]
@blaino is this ticket replaced by [#447](https://github.com/ozone-development/ozp-center/issues/447#issuecomment-161395269)?

**Comment by blaino** [comment]
@bhalt, I think so, provided everyone agrees #447 captures our discussion earlier.

**Comment by tonyalletag** [comment]
please refer to #447
