### ISSUE TITLE
Listing Management - "Pending, org." number indicator is cut off when a state is highlighted

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#183]
When you Highlight a state, numbers show for Published, needs action, Returned, draft...but the number seems to get cut off after pending, org.

**Comment by clarkjefcoat** [comment]
Is this the same as #152 or is this something different?

**Comment by sdeighan** [comment]
We have so far been unable to reproduce this in order to adjust the styling. Are there any additional details you could provide? @jloveland18

**Comment by jloveland18** [comment]
no..i really can't..all i did was go back and forth clicking on all, published, needs action, pending org., returned, and draft..but it doesn't seem to be happeing now..i can't recreate it either at the moment.
