### ISSUE TITLE
Search & Discovery - Return in Search box moves focus to Listing Type filter

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#187]
In Center, type mail in the search field and hit enter, the focus shifts from the search field to listing type.
This field should display when selected.

**Comment by sdeighan** [comment]
Could you explain a little more about what you feel the issue is? It's not clear what you were expecting to happen. Did you expect to skip the other fields and go to the Search Results? Or did the Listing Type filter not respond like you thought it would? Or was it a different problem?

**Comment by kgordon-1** [comment]
I expected for my cursor to stay in the search field until I was ready to
move it to the next field.

**Comment by sdeighan** [comment]
Ok, since there is no button, that's the default response for the return key. The only thing we can really do is make the return key do nothing; it should leave focus on the Search Box, but I've never seen it implemented like that before, so it's hard to tell at this point.

**Comment by clarkjefcoat** [comment]
@bhalt - Can we revisit this?  Whenever anyone from management gives a demo they _always_ press enter in the search box.  I know that sdeighan was not in favor of having the enter press do nothing, but that is my preference.  What do you think?

**Comment by bhalt** [comment]
@clarkjefcoat I'm fine with it doing nothing .. but I don't know if that is needed to step through the platform using JAWS. Referring to @SOAP1914. If he doesn't need that function, than I'm good with disabling it.

**Comment by SOAP1914** [comment]
@bhalt @clarkjefcoat This will not effect JAWS (being that we "tab" to the next field and push "enter" to enter the field) but if we can get "enter" to focus on the Search Results or just disable it being that its in a <form> tag

**Comment by tonyalletag** [comment]
Lets schedule this for the next iteration.

**Comment by tdressel** [comment]
Passed on Chrome.
