### ISSUE TITLE
Create/Edit Page - Adding multiple screenshots has the incorrect behavior

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#189]
Currently when you add a screenshot if it is not fully populated (i.e. Full Size image is not uploaded) and you hit the Add New button nothing appears to happen however when you add the Full Size image and save the new screenshot appears for when you hit the Add New button.

Steps: 
1) Create/Edit a listing
2) Add a screenshot and upload a preview image
3) Hit Add New 3 times (nothing appears to happen)
4) Add the Full size image for the screenshot in step 2 and Save
5) 3 New screenshots now appear

The expected result should be to either show the screenshots being added or disable the Add New button until the screenshot has both images.

**Comment by akonsowski** [comment]
tried testing in chrome browser and was unable to recreate the bug. The third screenshot pops up and user is unable to submit unless all images and classifications have been added to the screenshot.

**Comment by tdressel** [comment]
Also tried recreating but unsuccessful.  Validation does not allow user to add a preview screenshot without a fullsize screenshot. It also will not allow you to add and save blank screenshots.
