### ISSUE TITLE
Create/Edit Page - Validation messages for Resources are not appearing

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#191]
Add a resource on the Create/Edit page and leave the two fields blank and save. A red line where a validation message should appear shows up but there is no message in the red area. Validation messages should be populated on the page.

**Comment by mparizernc** [comment]
All Browsers

Verified that the Resources now shows errors correctly.

**Comment by jloveland18** [comment]
Tested in staging 0.7.6
All Browsers

Verified that the Resources now show errors correctly.
