### ISSUE TITLE
Create/Edit Page - Add portion markings to listing URL

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#192]
Depends on https://github.com/ozone-development/ozp-rest/issues/60

**Comment by sdeighan** [comment]
People will also need to be able to identify the appropriate levels of sensitivity for each URL and #193, right? If so, we should also update the UI in order to allow this. If not, is there a blanket level that we will be associating with them automatically?

**Comment by sdeighan** [comment]
IOB Mockup
![mp_createeditform_details](https://cloud.githubusercontent.com/assets/7987446/7165267/91177792-e374-11e4-8539-2835c9c18643.png)

**Comment by clarkjefcoat** [comment]
Listing URL was the only one called out during our security review, but we need portion marking on all URLs.

**Comment by blaino** [comment]
We have a marking for the whole listing as of #448. This marking covers the url. @tonyalletag, recommend closing.
