### ISSUE TITLE
Create/Edit Page - Labels for Resources and Screenshots do not appear if you have more then 10 items

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#194]
On the Create/Edit page I added more then 10 screenshots and resources and past 10 the labels (field name and descriptions) do not appear. Only the text boxes and shown.

**Comment by tonyalletag** [comment]
@tdressel is this still and issue? Don't we have a limit

**Comment by tdressel** [comment]
Logged in as Jones/Org Steward/Admin
Submitted a new listing. 
Added one screenshot at a time while saving until 10 screenshots total.
When adding the 11th one 
RESULTS - see attached screen shot.
.

**Comment by tdressel** [comment]
<img width="1258" alt="screen shot 2016-04-05 at 1 08 35 pm" src="https://cloud.githubusercontent.com/assets/5015370/14291050/951eaf1c-fb2f-11e5-9756-eb289c7a5890.png">
<img width="1132" alt="screen shot 2016-04-05 at 1 08 11 pm" src="https://cloud.githubusercontent.com/assets/5015370/14291051/966cb3dc-fb2f-11e5-8a01-1fde0b607845.png">

**Comment by tdressel** [comment]
Add New button is removed after 10 screenshots and 10 resources.

**Comment by tdressel** [comment]
Passed on Staging.
