### ISSUE TITLE
Create/Edit Page - Mark "Intents" field as optional

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#200]
This field needs to have "input-optional" added to the field's classes property

**Comment by mparizernc** [comment]
All Browsers

Verified that intents are marked as optional.  Ready for Prod testing when pushed.

**Comment by jloveland18** [comment]
Tested in staging 0.7.6
All Browsers

Verified that intents has (Optional) next to it. Ready for Prod testing when pushed.
