### ISSUE TITLE
Notifications - Created-At should show the date & time that the notification was created

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#203]
Created-At needs to be the date and time that the notification was created.
It's currently showing the time that the notification expires.
![notificationscreatedat](https://cloud.githubusercontent.com/assets/7987446/7208298/c6f0982c-e50d-11e4-9b28-b45f129c4121.png)

**Comment by hoganmaps** [comment]
I was looking at this ticket so I could make webtop notifications just like it (and talking with Clark about it). He mentioned putting the local time when the notification was created instead of zulu/gmt for center, hud, and webtop.

**Comment by sdeighan** [comment]
It is supposed to be in local time for the user; my computer was set to Eastern Daylight when the screenshot was taken. So, it indicates EDT after the time.

**Comment by hoganmaps** [comment]
sorry about that. I was a little confused about how the date was being stored and how it was being displayed but I got it now.

**Comment by mparizernc** [comment]
IE is showing NaN/NaN/NaN  Invalid Date

**Comment by jloveland18** [comment]
tested in ci-develop 0.7.4

IE still shows NaN/NaN/NaN Invalid Date

**Comment by kgordon-1** [comment]
Tested in staging and in all 3 web browsers
The date and time displayed is the date and time the note was created.

However, Eastern Daylight Time is displayed 2 different ways.  IE displays EDT and the other 2 browser spell the words out.  Not a big deal.  It works.
