### ISSUE TITLE
Create / Edit Page - Unable to save Listing if only one Screenshot image (of 2) is added 

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#205]
In List Management, add a screenshot and click save. A red bar is displayed under Screenshot and the listing in not save.  Also unable to submit listing because Screenshot is a required field.

**Comment by sdeighan** [comment]
This bug is a result of there being 2 required parts to the one field; @stephanieerin is going to have a look and see if she can separate them out for save

**Comment by stephanieerin** [comment]
The second part of this isn't a bug, you won't be able to submit without a screenshot.

**Comment by clarkjefcoat** [comment]
Can we improve the wording to make it clear that a preview and a screenshot are both required?

We had an outside user complain about this as well during testing.  The words say you have to add 1 screenshot, which is true, but you have to add two images (preview + screenshot).

**Comment by sdeighan** [comment]
Wording updated - the messages sit in the React-Commons repo, so in order to get the new message, you will need to delete the node modules and reinstall them

**Comment by kgordon-1** [comment]
I can create this error with one or both images.

**Comment by kgordon-1** [comment]
I take it back.  I can now save with both images.  Yesterday I could not.

**Comment by stephanieerin** [comment]
You can now save a listing with any combination of screenshots. You will still see the error when trying to submit without screenshots.

**Comment by stephanieerin** [comment]
This required a back end change, make sure you have the latest `develop` in ozp-rest as well

**Comment by mparizernc** [comment]
All Browsers

I was able to save screenshot images with only one screenshot for draft listings.  Submitted listings throw errors.  There were some outstanding issues found with screenshots for IE11 that have been put in a separate ticket #227.

**Comment by jloveland18** [comment]
Tested in Staging 0.7.6

All Browsers

I was able to save screenshot images with only one screenshot for draft listings.
