### ISSUE TITLE
Create / Edit Page - Unsecure Phone number field allows alpha characters

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#206]
Secure Phone will not allow you to enter alpha characters or invalid characters but Unsecure Phone number field will accept alpha characters if Secure Phone has a valid number.  The same validation on Secure Phone should pertain to Unsecure Phone field too.

**Comment by sdeighan** [comment]
We have tried Chrome, FF, and IE and every strategy we can think of to get this thing to take alphabet characters and we can't reproduce this bug. Any other details you can give us?

**Comment by kgordon-1** [comment]
Make sure you have a valid number in Secure Phone number field.
Both numbers are displayed with the red bar when you first come in (that is
a problem).  I enter a valid number in Secure Phone number field and that
turns off the red highlights for both fields.  I than enter "as" and no
error, no red highlights nothing happens.

 I can reproduce it now and if you have access to the high side I can email
it to you.

**Comment by wski** [comment]
I'm unable to reproduce this, It may have been a browser specific issue. @clarkjefcoat if you could test before calling it a non issue just to be sure.

**Comment by clarkjefcoat** [comment]
@wski - I agree with you.  It should be marked resolved because it can't be reproduced.  (Chome, IE10, FF)

**Comment by clarkjefcoat** [comment]
I also tried to reproduce this issue in production.  I can't duplicate the error.
