### ISSUE TITLE
Detailed View - Word wrap not functioning in What’s New

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#207]
Word wrap not functioning in What’s New
In list management, click on SpaceChrome Gordon listing, displays the details.  Please note that the What’s New line over takes the next column.

**Comment by mparizernc** [comment]
Not all developers have access to the system you are testing against.  Please add content in the ticket so that the error can be reproduced in other environments.

**Comment by clarkjefcoat** [comment]
I think the issue is that it doesn't force line breaks within a string of text with no spaces.  I hope this will be a rare occurrence.  I'm ok with leaving this bug until after IOB.

![image](https://cloud.githubusercontent.com/assets/7015118/7262020/3a2303b4-e844-11e4-92b9-b1523769e924.png)

**Comment by tonyalletag** [comment]
this is fixed in staging and production
