### ISSUE TITLE
OzoneConfig - Update the file to match Webtop & HUD

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#211]
Center, HUD, Webtop, & React-Commons OzoneConfig files should match.

Need to add IWC to the Center Config file

**Comment by sdeighan** [comment]
Added in React-commons

**Comment by mparizernc** [comment]
Verified that the OzoneConfig.js has the same links across the products.

**Comment by clarkjefcoat** [comment]
@kgordon-1 - I consider this bug as not end-user (or QA) testable.  The purpose of this fix is to make deployment easier in staging and production.  This change does not effect the end-user experience in any way.
