### ISSUE TITLE
Global Toolbar - Selecting Developer Resources should open into a new tab

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#212]
1. Select the three Horizontal bars in the top right corner.
2. Select Developer Resources.
3. It takes over the current tab and you can't go back to AppsMall.

**Comment by mparizernc** [comment]
All Browsers

Verified in all of the products that the Dev Resources open in a new tab.  Ready to be tested in prod.

**Comment by kgordon-1** [comment]
Tested in Staging
Developer Resources opens a new tab.
