### ISSUE TITLE
Listing Management - Preview does not work if full description is empty

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#213]
1.  Go to Submit a Listing
2.  Enter a Name and Listing Type, but do not enter any descriptions
3.  Save as a draft
4.  Go to Listing Management and click on the item you just saved.  The preview is not displayed.

![image](https://cloud.githubusercontent.com/assets/7015118/7307213/35e2e260-e9d9-11e4-8ac0-6f5abfe9a38e.png)

**Comment by mparizernc** [comment]
All Browsers

The Detailed View now opens correctly when there is no description.  This is ready to be tested in Prod.

**Comment by jloveland18** [comment]
Tested in staging 0.7.6
All Browsers

The Detailed View now opens correctly when there is no description. This is ready to be tested in Prod.
