### ISSUE TITLE
Accessing 'Submit a Listing' from any UI in OZP

### ISSUE THREAD

**Issue by TheAndyStumpf** [ozone-development/ozp-center#219]
When a user clicks 'Submit a Listing,' the toolbar indicates they are taken to Center.  When you're done submitting an app for listing, is the user taken back to the UI they were using (for example, clicking 'Submit a Listing' from Webtop) or do they have to manually navigate themselves back?

**Comment by mparizernc** [comment]
When the user is done they are taken to the My Listings page not to the where they navigated from originally.

**Comment by tonyalletag** [comment]
Not an issue or to low priority
