### ISSUE TITLE
Create/Edit Page - Errors display when fields are added

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#220]
When creating a Listing, click Add New for Resources, Screenshots and Contacts, they all display red highlights as if the user had entered an error.  No information has been enter and the submit button has not been selected.  A user should not receive error message when there is not error .

**Comment by sdeighan** [comment]
@tonyalletag @TheAndyStumpf I know that you wanted this to get done previously, but I can't seem to find another ticket for it. What timeline did you have in mind for this?

**Comment by sdeighan** [comment]
Feedback indicates IOB bug, adding appropriate tags

**Comment by stephanieerin** [comment]
I looked into this previously. Screenshots should be fixed currently, Resources would be another easier fix but Contacts is probably not super realistic given the timeline. Anyone who picks this up should talk to me about the work done for Screenshots.
