### ISSUE TITLE
Detailed View - URL length 

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#221]
In listing management, URL field, enter a URL with 75 characters or more and in the Details section it overruns into the next column.  It should wrap around Please see AirForceOne as an example.

**Comment by sdeighan** [comment]
Could you please copy the URL from "AirForceOne" into the ticket? We don't have access to that listing

**Comment by clarkjefcoat** [comment]
Here is an example from Location Viewer from the DI2E site.  Note how the URL overflows on top of the Associated Organizations text.

![image](https://cloud.githubusercontent.com/assets/7015118/7351348/9aa0b3b6-ecd2-11e4-9a68-f6c6f097bbd8.png)

**Comment by sdeighan** [comment]
Since this is the detailed view, would it be possible to show the whole URL and have it wrap inside the column to constrain the width? It would be useful to have the full URL visible somewhere and this is really the best place.

**Comment by wski** [comment]
@sdeighan I think setting a constrained width to the column it's in should do that automagically, then we can just remove the logic inside the component that adds the ellipsis

**Comment by hoganmaps** [comment]
According to @clarkjefcoat - the original issue of the URL being too long is fixed. The url is truncated with ellipses, but the full url works. Clark said a new ticket can be opened to take off the ellipses and wrap the URL per Sarah's message

**Comment by kgordon-1** [comment]
Passed -- Tested in STG
Verified fixed by creating a listing with a long URL.  Previewed listing and URL is displayed with  …..
