### ISSUE TITLE
Create/Edit Page - Encoded URLs should not change after edits

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#222]
This is related to the change to allow users to specify working URLs with spaces in them as the listing URL.  As it currently works if a user enters "https://www.google.com/webhp?gws_rd=ssl#q=hello world" it gets entered into the database correctly as "https://www.google.com/webhp?gws_rd=ssl#q=hello%20world".

However if the user edits that listing, the listing URL is displayed in the edit box as "https://www.google.com/webhp?gws_rd=ssl#q=hello%20world".  When the URL is not changed, but the listing is saved, the listing URL is saved as "https://www.google.com/webhp?gws_rd=ssl#q=hello%2520world".

Note the difference, now the existing % has been url encoded into %25 resulting in a URL that no longer reflects the URL the user intended to input.

**Comment by clarkjefcoat** [comment]
Confirmed on ci-master during test of #260.

**Comment by kgordon-1** [comment]
Passed – Tested in STG
Verified fixed by adding spaces to URLs.  In the preview, the URL displays %20.    Believe this was fixed in 260
