### ISSUE TITLE
Create/Edit Page - (staging) Listing Type and categories are not always displayed

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#223]
In FF
From WebTop, click on triple lines and select submit a listing
Enter name
click to select Listing type. box is empty. Message says, "No matches found".   

Submit listing from Center and types are displayed.  
This behavior started with this release. 

Categories is also not displayed

**Comment by clarkjefcoat** [comment]
Closing as a dup of #266.  Even though this ticket is actually older, the other ticket has more recent discussion.
