### ISSUE TITLE
Saving invalid sized icons

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#225]
When you save an invalid sized icon with your listing, the dashboard toolbar icons get thrown off and fill the toolbar icon with pieces of the pictures instead of icons for them. For instance, one of my pix is a tulip field with a large piece of blue sky at the top. Listing Management let me save this image w my listing even though it was the wrong size. When I go to webtop, the webtop toolbar is just a highlighted sky blue thick bar, Indicative of the top of my tulip pic. I can select this and pull it up from the toolbar into the webtop space. At that point, you can see the full tulip pic. I showed this to Clark.

**Comment by sdeighan** [comment]
So, there are two factors at work with this bug.

The first issue is that Center does not validate the size of the icons that are uploaded. Unfortunately, this feature was determined to be beyond our resources for IOB. So, the backend does not check the image size (h x w) but it does check the file size (1 MB). While we would ideally like to force people to upload only the specifically indicated size, we don't have the ability to do that without the size checking feature.
@clarkjefcoat @tonyalletag @TheAndyStumpf Is the size checking feature still post-IOB?

The second issue is the display size of images. It is possible to indicate a specific image size that the image should display at, but that needs to be done in Webtop. Center does not have the ability to indicate or alter a display size in Webtop. For this part to be fixed, the issue should be introduced into the Webtop queue.

**Comment by clarkjefcoat** [comment]
I'm okay with leaving this as a post-IOB issue.  Since we are the ones approving apps we can leave this as a manual check for the AppsMall steward when the app is being reviewed for acceptance.

**Comment by clarkjefcoat** [comment]
This issue has been addressed in webtop in https://github.com/ozone-development/ozp-webtop/issues/555
