### ISSUE TITLE
Detailed View - When a Listing has a Full Screenshot but not a Preview screenshot the carousel does not show properly

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#226]
I created a draft listing that has a Full (large) Screenshot but did not have a Preview (small) Screenshot. When you view the detailed view the carousel gets truncated and does not show correctly. You need to have two screenshots to see the issue.

**Comment by rkenyon1969** [comment]
Do you have 5 minutes to walk me through this use-case? I'm confused at "When you view the detailed view the carousel gets". - thanks

@tdressel

**Comment by tdressel** [comment]
When I  Save a draft without a preview screenshot and with a full size screenshot it does not save anything in the screenshot section.  If I edit a listing and add a third screenshot (WITHOUT preview screenshot and WITH full size screenshot it does not save the added fullsize screenshot if the preview is missing.  I can't find a way to repro this.

**Comment by rkenyon1969** [comment]
@clarkjefcoat - based on Tiff's test, I suggest we close this. However, Tony put it in the que on 3/1/2016. Do we need to find the fix that may have resolved this? Do we need to test more? - thanks,

@tdressel 
@tonyalletag
