### ISSUE TITLE
Submit a Listing page - The screenshots are not being saved properly in IE11

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#227]
Test 1
Open the Submit Listing page in IE11.
Add a screenshot to the Preview Image
Hit Save and the image is moved to the Full Screenshot

Test 2 
Open the Submit Listing page in IE11.
Add a screenshot to the Both Images
Hit Save and the screenshot disappears

Test 3 
Open the Submit Listing page in IE11.
Add a screenshot to the Full Image
Hit Save and the screenshot disappears

**Comment by tonyalletag** [comment]
@mparizernc & @jal-vsi - Is this still an issue?

**Comment by mparizernc** [comment]
@tonyalletag This appears to be working now.
