### ISSUE TITLE
Search capability in listing management page

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#233]
As an OZP Admin or Org Steward I want to be able to search for specific listing on the listing management page so that I don't have to find them manually.

We have over a 150 Apps in the listing management page and the Org stewards need to keep clicking the load more apps button to get to the apps at the end of the alphabet.

**Comment by sdeighan** [comment]
Completely valid point; the only question is of implementation style. So, we had always planned to implement the "Table View" for the Listing Management pages, with the listing information in a table, with a search features and a few additional actions available in the table rows (to be decided at the time of implementation based on users' needs and available development resources). That view includes a search feature in the table which would be used to search for listings.

![tableviewonly](https://cloud.githubusercontent.com/assets/7987446/7569193/3176b0c6-f7d5-11e4-974c-52ed69525b5f.png)

The original users of the gallery view were not going to have that many listings. It was more for developers or organizations with around 10 listings. Creating the gallery view was more cost-effective to create for IOB, so table view was pushed until later.

Would you like us to pursue adding in the search functionality to the gallery view? Or would it be preferable to make the the table view a higher priority?

**Comment by tonyalletag** [comment]
No need to add the search capability to the gallery view as long as the table view has the ability to search.

**Comment by clarkjefcoat** [comment]
Temporarily moving back to "Working".  "Resolved" should mean that it is available on our testing servers.

**Comment by tdressel** [comment]
Passed on latest using IE, FF and CHROME.

**Comment by tdressel** [comment]
Passed on Staging
