### ISSUE TITLE
Create/Edit Page: Save feature in not consistent.  

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#234]
Using Prod data
System may or may not save a listing if all required fields are not populated. 
Example: Display a prod data in listing (AirHandler) no image added to listing, click save and the system displays "Saving Listing..." and spins.  Right click and select reload, the listing is displayed but   Listing Type data no longer populate the field. Cancel and reopen listing, enter required fields excerpt for images.  Saved and Spinning thing returns.

**Comment by clarkjefcoat** [comment]
This issue was caused by a database configuration problem in the staging environment.  Please open a new issue if this problem returns.
