### ISSUE TITLE
Preview needs refresh

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#235]
Using Prod Data:
In Listing Management, click on listing or use down arrow and click on preview.  Nothing happens until screen is refresh.  Then image is displayed

**Comment by sdeighan** [comment]
While trying to reproduce:
As an org steward for listing A and listing A was returned to the owner by the MP Steward, the first time you click "Preview" in the listing's menu, it will spend a while loading and won't open the modal. If you click it a second time, it will open the modal.
After I refreshed the Listing Management page, the problem also went away.

Does this sound about right?
If you have any additional information to reproduce this, that would be great

**Comment by tonyalletag** [comment]
Not an issue
