### ISSUE TITLE
Org content steward approved listing goes to "Needs Action" bucket 

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#236]
Content Steward approves listing.  That listing is displayed in the "Needs Action"  section instead of Org approved section.

**Comment by clarkjefcoat** [comment]
This is working as designed.

"Needs Action" always means that the listing needs action, but the reason for it appearing varies between the tabs.

My Listings - On the My Listings page the "Needs Action" label shows listings that you have submitted that have been rejected and need action from you to correct/resubmit them.

XYZ Listings - On the org steward listing page the "Needs Action" label shows listing that have been submitting and are awaiting your org-level approval.

All Marketplace Listings - On the admin listing page the "Needs Action" label shows listing that have been approved by the org steward, but are awaiting admin approval.
