### ISSUE TITLE
Detailed View - If a listing has more than one contact the Detailed View throws an error

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#243]
I created two Contact Types and added contacts for each type in the listing. When I viewed the listing in the detailed view (click on the listing on the discovery page) and tried to load the Resources tab it would not load.  The console was showing the error below.  If you go to Develop on DI2E and select AirMail you will see the issue.
```Uncaught TypeError: Cannot read property 'name' of undefined(anonymous function) @ main.js:70i.createClass.renderTechSuppot @ main.js:70i.createClass.render @ main.js:70(anonymous function) @ main.js:33(anonymous function) @ main.js:33v.Mixin._mountChildByNameAtIndex @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62(anonymous function) @ main.js:33R._performComponentUpdate @ main.js:33R.performUpdateIfNecessary @ main.js:33f.Mixin.receiveComponent @ main.js:40R.receiveComponent @ main.js:33(anonymous function) @ main.js:33R._performComponentUpdate @ main.js:33R.performUpdateIfNecessary @ main.js:33f.Mixin.receiveComponent @ main.js:40R.receiveComponent @ main.js:33v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62(anonymous function) @ main.js:33R._performComponentUpdate @ main.js:33R.performUpdateIfNecessary @ main.js:33f.Mixin.receiveComponent @ main.js:40R.receiveComponent @ main.js:33(anonymous function) @ main.js:33R._performComponentUpdate @ main.js:33R.performUpdateIfNecessary @ main.js:33a @ main.js:33r.perform @ main.js:41r.perform @ main.js:41h.perform @ main.js:33(anonymous function) @ main.js:33r.closeAll @ main.js:41r.perform @ main.js:41p.batchedUpdates @ main.js:78l @ main.js:33f.Mixin.replaceProps @ main.js:40(anonymous function) @ main.js:33A.scrollMonitor @ main.js:33A._updateRootComponent @ main.js:33A.render @ main.js:33(anonymous function) @ main.js:1a.createClass.statics.run.A @ main.js:61(anonymous function) @ main.js:61(anonymous function) @ main.js:73(anonymous function) @ main.js:73i.to @ main.js:73(anonymous function) @ main.js:61(anonymous function) @ main.js:73(anonymous function) @ main.js:73i.from @ main.js:73a.createClass.statics.dispatch @ main.js:61a.createClass.statics.handleLocationChange @ main.js:61(anonymous function) @ main.js:62o @ main.js:62s @ main.js:62```

**Comment by wski** [comment]
Related: #240 for better understanding of what was happening

**Comment by clarkjefcoat** [comment]
@wski - Although issue 240 was reported around the same time, it is not related to this bug.

**Comment by hoganmaps** [comment]
Tested this on the koalapepso widget, doesn't appear to be an issue any more

**Comment by kgordon-1** [comment]
This is fixed.
