### ISSUE TITLE
Create/Edit - Form resetting issues (continued)

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#246]

**Comment by wski** [comment]
Remaining issues: 

Form should reset when you hit 'Submit a Listing' from anywhere and not just when coming from editing another listing. 

Form validation should not be ran when resetting the form

**Comment by wski** [comment]
I don't think this is an issue anymore. @tdressel can you confirm?

**Comment by tdressel** [comment]
Steps used to test:
Menu | Submit a Listing | Fill out some of the form
Click Center Homepage icon (shopping bag icon in top left)
Clicked back to Submit a Listing
RESULT- The form was reset as it should be.
