### ISSUE TITLE
Detailed View - Standardize display of Contacts on the Resources tab

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#250]
On the right side of the Resources tab in the Detailed View the contacts are currently displayed in the order they were entered.  That means for some apps the "Technical Contact" is displayed before the "Management Contact" and for other apps "Management Contact" is shown first.

This a request for consistency between apps.  Always show the contacts in alphabetical order according to contact type.  (So in the example being discussed show the "Management Contact" first.)

**Comment by hoganmaps** [comment]
contact types are sorted alphabetically by contact type name in the resources view

**Comment by clarkjefcoat** [comment]
My test did not sort alphabetically.  It does however correctly group different Contact types together.

How things should be sorted is still a subject of some debate.  See #273.

Let's allow this ticket to proceed since it does fix the groups (but not order) of contacts.

**Comment by kgordon-1** [comment]
Tested in STG
Contacts are displayed as grouped together. For example, Techs are grouped together under one heading Techs. However, ticket 273 explains the order of the groups.  This ticket is closed.
