### ISSUE TITLE
Detailed View - Enlarge screenshot

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#251]
On the Overview tab of the Detailed View screenshots are shown.  In v1 each screenshot had a ribbon of text that said "Click to Enlarge".

In the current version when you click the small screenshot you are shown a larger version.  However, there is no indication on the small screenshot that a larger version is available.  Can we add something to let users know that large screenshots are available?

**Comment by sdeighan** [comment]
One major issue with this is that the cursor doesn't turn into a hand when the cursor is over the image - that will be a big improvement. I can probably do this part right quick - it's not too complicated.

Second, while there are some considerations with adding things (reduced visibility of details in that area and such), we can definitely add an icon overlay on hover that should indicate that the image can be enlarged. There are a few options we can choose from in how to implement it - I will workup some mockups and post them in here.

**Comment by sdeighan** [comment]
Started discussion in Slack #UX channel to discuss options, otherwise it could clutter the ticket

**Comment by tonyalletag** [comment]
Hover over changes the pointer to a hand which indicates the image can be clicked.
