### ISSUE TITLE
Create/Edit Page: Preview field copies its image to Full Size Image field

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#255]
If Preview Image Screenshots in populated when saving, the system automatically copies the image into Full Size Image field.  

The user may thing they populated the field.

**Comment by sdeighan** [comment]
Confirmed in development branch

**Comment by tonyalletag** [comment]
@jal-vsi can you confirm this is fixed?

**Comment by tonyalletag** [comment]
This is no longer an issue
