### ISSUE TITLE
Detailed View - URL updates with every change (Legacy adaptor listings)

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#260]
1. Log into Marketplace as Admin
2. Pick a listing and open detailed view
3. Open in Create / Edit or admin tab
4. Change anything about ~~the listing~~ a legacy adaptor listing (?)
5. Open Detailed View, Admin Tab
6. View details of the change that was made
7. See interesting URL information

![detailedview_changesbug](https://cloud.githubusercontent.com/assets/7987446/7684627/84362dc0-fd55-11e4-9d7e-630e34d9b49d.png)

Changes made for this image were (in chronological order)
1. Flagging as featured
2. Changing version number to 1.23

(Also, after I did the second change, I opened the Featured flag change again and instead of being below the launch URL change like the version number change details, it's now above the URL change - as seen in the screenshot.)

**Comment by mparizernc** [comment]
Looking at the screenshot this is accurate in the fact that the launch url is changing.  It appears that each time the listing is saved the % value gets encoded again for example if you have a % in the url it encodes with %25 and when you edit and save the listing it saves as %2525.

**Comment by wski** [comment]
I had fixed this in #222, not sure how it was undone. I'll have a look at it though; I was able to replicate it.

**Comment by clarkjefcoat** [comment]
Confirmed working on ci-master with Chrome, FF24 and IE9.

**Comment by kgordon-1** [comment]
Passed – Tested in STG
Verified fixed by modifying fields in listings and adding spaces to the URL.  In the preview, the URL displays %20 and the changes to fields are displayed correctly.
