### ISSUE TITLE
Create/Edit Page: Contacts are not displayed in the created order

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#265]
User's request: Display contacts in the data entry order.
Created a listing and enter the contacts in a particular order. 
Preview this listing and select Resources, the contact are not always in the data entry order.  

This order is changed upon save.

Soes comment:
The POCs are being saved in the database in a random order and not the order of their type id. And when they are retrieved from the database, it is done so in the order of their primary id.  Resulting in random shuffling of the POCs regardless of the type.

**Comment by sdeighan** [comment]
If we do data entry order, we can't do alphabetically ordered which was requested in #250

**Comment by tonyalletag** [comment]
No longer an issue
