### ISSUE TITLE
Create/Edit Page: In Chrome: Listing Type drop down menu is blank

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#266]
Creating a listing, the 1st time, the Listing Type drop down menu is blank.  

It does not happen all the time but I notes it when I first open Chrome and go to the Create a Listing page.

**Comment by sdeighan** [comment]
When this happens, is the initial selection blank? Or is the whole list blank?

**Comment by kgordon-1** [comment]
The whole list is blank.

**Comment by clarkjefcoat** [comment]
If I start in HUD or webtop and then choose "Submit a Listing" from the dropdown, the Create/Edit page ListingType dropdown is blank.  If I start in Marketplace and choose "Submit a Listing" the resulting Create/Edit page looks fine.

**Comment by wski** [comment]
Have we been able to replicate this?

**Comment by clarkjefcoat** [comment]
I still see this on ci-master in FF 24.0 with Ubuntu 14.04 when I click on "Submit a Listing" from HUD:

![image](https://cloud.githubusercontent.com/assets/7015118/8341287/e3482f26-1a91-11e5-8a74-d404da621665.png)

**Comment by blaino** [comment]
@wski, Please test this when you get a chance - the perfect opportunity for you to try BrowserStack.

**Comment by mparizernc** [comment]
@blaino I am not sure if this is because of this change but I am having routing issues now when trying to navigate away from the Create Listing page that I was not seeing before. 

Steps;
1 Navigate to the Create Listing page with Submit a listing
2 Select the listing management link next to the buttons
3 You remain on the Create page
4 Refresh and you are taken to the Listing Management page

Error in console:
```Uncaught TypeError: Cannot read property 'attr' of nullS.destroy @ main.js:66o.componentWillUnmount @ main.js:41P.unmountComponent @ main.js:33v.Mixin.unmountChildren @ main.js:62s.Mixin.unmountComponent @ main.js:62P.unmountComponent @ main.js:33P.unmountComponent @ main.js:33v.Mixin.unmountChildren @ main.js:62s.Mixin.unmountComponent @ main.js:62v.Mixin.unmountChildren @ main.js:62s.Mixin.unmountComponent @ main.js:62P.unmountComponent @ main.js:33(anonymous function) @ main.js:33P._performComponentUpdate @ main.js:33P.performUpdateIfNecessary @ main.js:33f.Mixin.receiveComponent @ main.js:40P.receiveComponent @ main.js:33v.Mixin._updateChildren @ main.js:62v.Mixin.updateChildren @ main.js:62s.Mixin._updateDOMChildren @ main.js:62(anonymous function) @ main.js:62f.Mixin.performUpdateIfNecessary @ main.js:40f.Mixin.receiveComponent @ main.js:40s.Mixin.receiveComponent @ main.js:62(anonymous function) @ main.js:33P._performComponentUpdate @ main.js:33P.performUpdateIfNecessary @ main.js:33f.Mixin.receiveComponent @ main.js:40P.receiveComponent @ main.js:33(anonymous function) @ main.js:33P._performComponentUpdate @ main.js:33P.performUpdateIfNecessary @ main.js:33a @ main.js:33r.perform @ main.js:41r.perform @ main.js:41h.perform @ main.js:33(anonymous function) @ main.js:33r.closeAll @ main.js:41r.perform @ main.js:41p.batchedUpdates @ main.js:79l @ main.js:33f.Mixin.replaceProps @ main.js:40(anonymous function) @ main.js:33A.scrollMonitor @ main.js:33A._updateRootComponent @ main.js:33A.render @ main.js:33(anonymous function) @ main.js:1a.createClass.statics.run.A @ main.js:61(anonymous function) @ main.js:61(anonymous function) @ main.js:74(anonymous function) @ main.js:74i.to @ main.js:74(anonymous function) @ main.js:61(anonymous function) @ main.js:74i.from @ main.js:74a.createClass.statics.dispatch @ main.js:61a.createClass.statics.handleLocationChange @ main.js:61(anonymous function) @ main.js:62o @ main.js:62s @ main.js:62```

**Comment by blaino** [comment]
@mparizernc, looking into it.

**Comment by blaino** [comment]
@clarkjefcoat found a problem where Tags isn't able to be updated.

**Comment by wski** [comment]
Verified that the tag fix works, Un-nessisary cancel timeouts and variables were removed. Everything looks :+1:

**Comment by mparizernc** [comment]
Verified in develop against all browsers that the drop downs are populated when you select Submit a Listing from each of the tools in the system.

**Comment by mparizernc** [comment]
On Staging verified the drop downs work coming from any of the tools when you select Submit a Listing.
