### ISSUE TITLE
Discovery page - Add "load more results" button to the end of all search pages

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-center#268]
When you search for apps (via text, categories, type, or agency), the backend returns the first 24 results in addition to a `next` url (if necessary) to get the next set of results (a common pagination strategy). Center currently has no 'load more' button on the search results page that allows the next set of apps to be retrieved.

**Comment by kgordon-1** [comment]
Passed -- tested on STG
Verified fixed by searching on a word like and which should bring up every app.  The Load More button appeared at the bottom several times.
