### ISSUE TITLE
Create/Edit Page: leaving page will no longer prompt warring message.

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#275]
Select Submit a Listing
Complete Name and Listing type.  
Select HUD.  No warring message is displayed.

if the users leave the page without saving there information, no message/warring message is displayed.  Not sure when this stopped working.  A user can loss all data.

**Comment by wski** [comment]
This should still happen, if this is in reference to navigating away from center completely that never poped a message but shouldn't be to hard to implement.

**Comment by tdressel** [comment]
passed on Latest

**Comment by tdressel** [comment]
Passed on Staging.
