### ISSUE TITLE
Add Docs and Videos to help modal, remove iFrame

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#278]
http://gyazo.com/de1f7ad43d5f9cf987a86e7d555dc3e5

**Comment by mparizernc** [comment]
@wski The modal shows actual links which leaves the user not knowing what they are clicking on.  They should be labels, see how webtop handles it they have labels that take you to the URLs.

**Comment by mparizernc** [comment]
Verified in all the browsers in Develop that the labels are shown instead of links and verified they open to the proper links.

**Comment by mparizernc** [comment]
Verified in all the browsers in Staging that the labels are shown instead of links and verified they open to the proper links.
