### ISSUE TITLE
Discovery Page - Direct link to search results

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#280]
A user requests the ability to give someone a link that goes directly to a search results page.  This feature was available in the old system and people used it.

**Comment by sdeighan** [comment]
![mp_searchresults_clickablepopover](https://cloud.githubusercontent.com/assets/7987446/8438192/5e29aa9a-1f32-11e5-8619-95350cb39597.png)

**Comment by blaino** [comment]
Verified works on ci-develop.amlng.di2e.net.

**Comment by mparizernc** [comment]
Verified in all browsers on the staging environment.

**Comment by blaino** [comment]
Retroactive :+1:
