### ISSUE TITLE
Listing Management - Sidebar counts incorrect

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#281]
The counts on the sidebar of the "All Marketplace Listings" in Listing Management are sometimes incorrect.  In particular I have seen an instance in production where the "Needs action" showed 0 until it was clicked when it then showed 2.

I have seen this in production, but do not yet have to steps to recreate it.

**Comment by tonyalletag** [comment]
@clarkjefcoat did this get fixed? I tried to reproduce in staging but it doesn't look like the filtering is working.

**Comment by clarkjefcoat** [comment]
This bug has not been directly addressed.  However a couple of fixes (#402, #406) have been made to the Listing Management page recently which may have had an impact on this issue.  I will ask the production Content Steward if this is still an issue.

**Comment by tonyalletag** [comment]
content stewards confirmed he hasn't seen this issue an awhile and was not able to reproduce it.
