### ISSUE TITLE
Global Toolbar - Disable Notifications styling when there are no notifications

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#282]
When there are no notifications, the notifications menu/button should be disabled. On click, the styling should not change.

**Comment by mparizernc** [comment]
@wski the notifications button is disabled when the menu button is clicked when there are notifications now.  It should be enabled if it is clicked and there are notifications.

**Comment by wski** [comment]
Are you using the new ozp-react-commons? 
<img width="172" alt="screen shot 2015-07-20 at 11 14 04 am" src="https://cloud.githubusercontent.com/assets/1770198/8779278/a407d796-2ed0-11e5-8de9-3542969eea1c.png">
<img width="301" alt="screen shot 2015-07-20 at 11 14 40 am" src="https://cloud.githubusercontent.com/assets/1770198/8779277/a4054c06-2ed0-11e5-81b8-6a8366f2f706.png">
<img width="179" alt="screen shot 2015-07-20 at 11 14 51 am" src="https://cloud.githubusercontent.com/assets/1770198/8779279/a408fffe-2ed0-11e5-9705-39129285399f.png">

Above shows it working as expected, can you provide steps to reproduce?

**Comment by mparizernc** [comment]
@wski you have it in the screenshot above.  The bell should be the same gray color as the notification box.

**Comment by wski** [comment]
Oh right, I see now. I'll fix that up and comment here when done. It might
require more updates to commons

**Comment by blaino** [comment]
:+1:

**Comment by jal-vsi** [comment]
Verified pass on all 4 browsers using Admin to create notification and testUser1 viewing it.  The notification block and bell turns gray when selected.

**Comment by mparizernc** [comment]
Verified the styling is correct on Staging, using IE10, FF and Chrome.
