### ISSUE TITLE
Create/Edit Page unable to delete the last character in What's New field

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#284]
The last character in the What's New field will not allow you to delete it.

**Comment by blaino** [comment]
The first comment here refers to a first unsuccessful attempt to fix this problem. That solution failed on computers with less cpu/memory. Adding lots of text to a textarea field and holding down the delete caused unpredictable jumps, skips and reintroduction of deleted data. All of that said, the idea behind this unsuccessful solution I believe is still sound: a form with validation shouldn't warrant React optimization hints with shouldComponentUpdate().

**Comment by wski** [comment]
verified it's working on my end, passing to CI-QA

**Comment by mparizernc** [comment]
I was able to delete all of the What's New with no chars left behind.  I tried before saving the value and after saving the value.  Works on staging in each browser.
