### ISSUE TITLE
Create/Edit Page - Cancel button not functioning 

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#285]
In Listing Management, select an app that has been approved for center (not sure it that have any thing to do with it).
Blank or delete the URL 
Click the backward arrow, get pop up warring, click Cancel.  Would not let me cancel 
Click ok.  Takes you into WebTop.

Able to reproduce this in ci-master

Currect behavior, Cancel should keep me in the listing and OK should have taken me to Listing Management.

**Comment by tonyalletag** [comment]
Not a bug
