### ISSUE TITLE
Scroll down to make load more less confusing

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#286]
New enhancement
In center, when you click on Load More, the next set of apps is added to the bottom of the previous apps.  It should continue to do this.  However, the user must uses the scroll bar to navigate to the next set of apps.
It might be nice to have the screen refresh and expanded the list but display the next set of apps, instead of the user using the scroll bar to display them.  If the user desires to view the previous apps they can scroll up.  
It would be nice to have this feature for all searching capabilities.  A good example is when a user selects the Category, Viewer to search on.  To select Viewer the user must scroll down and select it.  However, to see the results, the user must scroll back up to the top.  The system should automatically refresh and display the apps the user is searching for.

**Comment by tonyalletag** [comment]
@wski Anybody working on this. Were there reasons we didn't implement this?

**Comment by wski** [comment]
It still needs to be done, I've been focused more on the new backend and help. If this is desired to be done soon I can switch gears and knock it out.

**Comment by tonyalletag** [comment]
Closing this for now.  @arw180 & @wski let make sure there is a ticket in the new backend to allow for continuous scrolling so we can remove the load more button
