### ISSUE TITLE
Listing Management - Notify admins when a listing is deleted

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#292]
When an app is deleted admins should be notified or the fact it was deleted should be recorded on the "Recent Activity" tab.  Currently there is no record that an app has been deleted or that a deleted app ever existed.

**Comment by mparizernc** [comment]
@clarkjefcoat This is a duplicate of #87

**Comment by clarkjefcoat** [comment]
As noted above, this is a dup of #87
