### ISSUE TITLE
Create/Edit Page - For short description show a countdown for the number of characters remaining.

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#293]
When entering the short description show the number of characters remaining so submitters know how long their descriptions can be.

**Comment by mparizernc** [comment]
@wski This should stop the user typing at 0 not go into the negative.

**Comment by wski** [comment]
We came to the conclusion to leave the negative so that the user can see how many characters they are over by. The same functionality exists in Twitter, Facebook and many other platforms. However if @bethany and @sdeighan requested that it stop at zero its pretty easy to switch over

**Comment by sdeighan** [comment]
It's considered a best practice with form fields to only allow valid input wherever possible. I would strongly support just putting a limit on the text input field at the maximum number of characters. @bhalt Would you agree?

**Comment by wski** [comment]
If they were to copy paste from somewhere though it might be harder for them to figure out how much they need to trim off if it just says `0` was my only thought

**Comment by bhalt** [comment]
I'm good with leaving the negative as long as there is an error message after they go over 100, which there is. I agree with Matt about copying and pasting from elsewhere and using the text field to crop it down. I've done this before and it's very nice to be able to do it in the native environment with a live countdown, rather than having to open another program.

**Comment by sdeighan** [comment]
If we want to do that, it's fine, but then I would suggest we redo the message. Negatives out of 100 is pretty confusing. I would either continue the count and have it stay red or switch the text to (# characters over maximum of 100.)

It's not possible to have a negative number if there's text in the box and, while I understand what you were going for, it may lead users to believe that there's an error with the counting mechanism.

**Comment by bhalt** [comment]
I just now saw the screenshots (I'm not at a place I can build). Agree with Sarah -- let's change the message under the form field to "__ characters remaining" when under the limit and a red "__ characters over the limit" when over the limit. Thoughts @sdeighan?

Also, can the red highlight above the field just be on the "Must be 100 characters long or less" text when a user goes over the limit, and not also on the "May contain letters, numbers, or symbols" ?

**Comment by sdeighan** [comment]
We had the same concern, either one sounds good to me.

The modified red highlight makes sense to me - I'd be all for it. I'm just not sure about the technical side, those errors are tricky unless they've been re-written recently. If we can get that changed, I'm totally on board.

**Comment by jal-vsi** [comment]
Verified pass on all 4 browsers using testUser1: Error message if you type above 100, won't save >100, saves at 100 or less

**Comment by mparizernc** [comment]
Verified in Staging that a user cannot save a listing if short description is greater then 100 characters as an error is thrown.  Tested against IE9, FF and Chrome.
