### ISSUE TITLE
If a user clicks to remove a bookmark that is living on a dashboard, show modal asking for verification.

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-center#299]
This modal should pop up when a user clicks to remove a CURRENTLY USED bookmark from the HUD.
<br>
![uploads/f968fa56-197e-4e0a-b1c9-e541fff51bcc/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff968fa56-197e-4e0a-b1c9-e541fff51bcc%2Fblob)

**Comment by clarkjefcoat** [comment]
This issue was re-created at https://github.com/ozone-development/ozp-hud/issues/100

**Comment by bhalt** [comment]
@clarkjefcoat that was actually intentional -- bookmarks can be removed in both HUD and Center so this notification should be in both places if it is actively on a dashboard.

**Comment by bhalt** [comment]
Oh, whoops, didn't realize this was on the duplicated issue I had deleted. my bad.
