### ISSUE TITLE
Create/Edit Page - Error Pop-up shown when there are no errors

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#301]
1. From the dropdown menu choose "Submit a Listing"
2. Fill-in a subset of the required fields
3. Press Save
4. Press Submit, you will get an error as you have not filled in all required fields.  This is correct.
5. Update one of the fields you have already entered.
6. Press Save.
7. You will get an error pop-up.  If you press Show Errors, you will not be shown any errors because there aren't any.  The last error pop-up should not appear.

**Comment by mparizernc** [comment]
I have verified that the error message no longer appears when you save after trying to submit without all the necessary fields populated.  This passed for develop.

**Comment by mparizernc** [comment]
Verified on Staging that I can save even after a submit fails with validation errors.  Works on all browsers.
