### ISSUE TITLE
Global Toolbar - "Menu" Tooltip activating when hovering over menu items

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#302]
![center_menutooltipbug](https://cloud.githubusercontent.com/assets/7987446/8381439/9d2da8a4-1bf9-11e5-8eb4-3938c329e8e7.png)

1. Go to Center
2. Open Menu
3. Hover mouse over a menu item
4. Tooltip "Menu" will appear over the menu icon

**Comment by tonyalletag** [comment]
Not a bug
