### ISSUE TITLE
Clicking home in the sidebar does not reset types or organizations 

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#308]

**Comment by wski** [comment]
@sdeighan @bhalt I noticed there are x buttons on the type and agency dropdowns but was it intended that they would not be cleared when clicking the home button in the sidebar?

**Comment by bhalt** [comment]
I think you're right -- filters can be cleared from the filter but it seems like it should also be cleared when you go to the Center home. @sdeighan designed most of the Center UX however and may have a different comment when she gets back next week .. I'll defer to her on this.

**Comment by wski** [comment]
alright, I'm going to go ahead and fix this now and if @sdeighan decides otherwise we can revert it. I'd like to get a fix in before iteration tomorrow because the new features with search make this bug more apparent

**Comment by blaino** [comment]
Verified on ci-develop.amlng.di2e.net.

**Comment by mparizernc** [comment]
Verified that the home link now clears all filters on staging in each of the browsers.
