### ISSUE TITLE
Listing review metrics is reporting on incorrectly

### ISSUE THREAD

**Issue by gziskind** [ozone-development/ozp-center#314]
When you view a listing, it is being reported as a "Listing Review" instead of a "Listing Review View". But when you review a listing is correctly being reported as "Listing Review"

It also seems to report 2 listing review events for any single event

**Comment by clarkjefcoat** [comment]
How should this work?  Are there supposed to be two categories - "Listing Review" and "Listing Review View"?  

What should get counted in "Listing Review"?  Only ratings with comments or ratings without comments as well?

The current counting of all views as "Listing Review" is causing some confusion.  Can you spell out what the "right" solution will look like?

**Comment by gziskind** [comment]
In the center code I am seeing 2 methods to report metrics about listing reviews. One is called "trackListingReview," which reports an event of "Listing Review" and the other is called "trackListingReviewView," which reports an event of "Listing Review View"

It seems as though the intention was for Listing Review to track when a listing gets reviewed (I didnt really know about the difference between ratings with comments and ratings without comments). And then the Listing Review View was to tracking when someone reads the review tab of an application.

The issue is that trackListingReviewView is never called. And it looks like trackListingReview is called twice in the file app/js/services/ListingService.js:132,136

**Comment by tonyalletag** [comment]
@wski & @gziskind Can this be closed?

**Comment by wski** [comment]
This was fixed, @gziskind if you can verify I'll close.

**Comment by gziskind** [comment]
Yes this is fixed
