### ISSUE TITLE
createEdit: preview shows "Not provided!" for What's New when actually provided

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#324]
The fix (db76913) for #256 and #284 introduced a regression where the preview for What's New is not updated.

**Comment by jal-vsi** [comment]
Verified working (testUser1) in both Create/Preview and Listing Mgmt/Preview for all browsers (IE9, IE11, FF24, CH36)

**Comment by mparizernc** [comment]
Verified that the What's New text appears and is removed on the Details tab of the Detail View on the Create/Edit listing page before and after saving as well as on the Detail View on Listing Management. Tested on Staging with IE9, FF, Chrome
