### ISSUE TITLE
Tags cannot be added to a listing

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#328]
I was creating a listing and I tried to add a tag. Every time I try and add a character for a tag it is removed.  I am not seeing any errors in the console.  This is a showstopper since it is a required field.

**Comment by blaino** [comment]
Fixed by #326

**Comment by mparizernc** [comment]
All browsers 

Verified that the develop allows tags to be added to a listing.

**Comment by mparizernc** [comment]
Verified in Staging that Tags can be added to existing and new listings.
