### ISSUE TITLE
Severe performance problems in Firefox 24

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-center#329]
In our production environment, the FF24 user experience is pretty bad as compared to Chrome and IE9. For example:

* Time to load a listing preview modal in IE9/Chrome: < 1 second. FF24: 5-7 seconds
* Time to close a listing preview modal in IE9/Chrome: < 1 second. FF24: 2-3 seconds

The performance problems all appear to be JS related. Unfortunately, these issues are much less obvious outside of the production environment. Is there a way to disable certain JS animations in FF to improve user experience?

**Comment by tonyalletag** [comment]
@wski - Can you update this ticket. The updates you made had significant improvements in performance on production

**Comment by wski** [comment]
This was fixed by disabling animations in CSS & jQuery along with Bootstrap when firefox is used.
