### ISSUE TITLE
Center - Agency must be reported with the metadata sent to the the metrics application

### ISSUE THREAD

**Issue by gziskind** [ozone-development/ozp-center#330]
Users of the metrics application have requested to be able to sort by applications according to which agency submitted the application, so in order for this data to be logged, the center application must report the information to the metrics application. This can be done by reporting an "Event Name" of the agency when an application launch is tracked.

**Comment by jal-vsi** [comment]
Passed test in all 4 browsers on Master (Admin or Org Steward):
Metrics page: Event Categories/Event Name/Applications (+)
1) Day range - record TO/TO2/TO3 numbers, open apps in all, F5, recount to verify
2) Same test for Week, Month, Year, Date Range
