### ISSUE TITLE
Search - A shared search link with only orgs (or only listing type) does not work

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#334]
Shared search links such as:
- .../center/#/home///Web%20Application/
- .../center/#/home////Test%20Organization

always report "No results found" even when there are results.

An ugly workaround to get results is to type and then delete something in the search text box.

**Comment by jal-vsi** [comment]
Shared search (Search Results Share) passed in Master with all 4 browsers and 3 users: User, Org Steward, and Admin.

**Comment by mparizernc** [comment]
Verified that the Search is passed correctly when searching for an Org or Type with a shared link.  Verified in IE10, FF and Chrome on Staging.
