### ISSUE TITLE
Add static number counts to Organizations in Center

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-center#342]
See screenshot:

![center_catorgcounts](https://cloud.githubusercontent.com/assets/8047457/8984567/58da5cda-36a0-11e5-8a73-a0f800dcf617.png)

HTML inside each `<li>` after the name:
```<span class="badge">#</span>```

CSS:
```.badge {
  float: right;
  background: #e0e0e0;
  font-weight: bold;
  color: #888;
  font-size: 10px;
  line-height: 1;
  margin: 7px 20px 0 0; /*margin only on categories, not orgs*/
}```

**Comment by blaino** [comment]
@jal-vsi This ticket is ready for a first look.

**Comment by blaino** [comment]
Note that this ticket originally specified Organization counts and Category counts. While we may still do Category counts, this first slice of functionality is just the Organization counts.

**Comment by jal-vsi** [comment]
Passed Org Counts test with 4 browsers (both User and Admin).  Checking
individual apps in TO (23), TO2 (12), TO3 (9), and all combinations (35,
21, 32, 44).

On Tue, Aug 18, 2015 at 8:40 AM, Blaine <notifications@github.com> wrote:

> Note that this ticket originally specified Organization counts and
> Category counts. While we may still do Category counts, this first slice of
> functionality is just the Organization counts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/342#issuecomment-132194471>
> .
>



-- 

Thanks,

Jim Laughter

Systems Test

Ventura Solutions Inc.

131 National Business Parkway

Suite 120

Annapolis Junction, MD 20701

(301) 623-4156

jlaughter@vsi-corp.com

**Comment by jal-vsi** [comment]
Passed Org Counts (in Develop) with 4 browsers having Admin change Org ownership and confirming those counts within TO, TO2, and TO3 change accordingly.

**Comment by jal-vsi** [comment]
Passed Org Counts test (in Master) with 4 browsers (User, Org Steward, Admin).  Checked individual apps TO (21), TO2 (13), TO3 (10), and all original combinations.  Changed and checked new combinations after Org Steward changed Org ownership ratio of all 3 Orgs.  Changed and checked new combinations after Admin changed Org ownership of all 3 Orgs; ending with TO (15), TO2 (15), and TO3 (14).

**Comment by clarkjefcoat** [comment]
Tested in staging on IE9, FF24 and Chrome36
