### ISSUE TITLE
Submit a Listing bug

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#343]
When submitting a listing the text in "Usage Requirement" does't wrap when viewed in Details (text does wrap in "What's New") as noted in the attached file.
![submit listing](https://cloud.githubusercontent.com/assets/13243617/9014300/9c2c0624-378f-11e5-9485-04a0c46445af.PNG)

**Comment by jal-vsi** [comment]
Passed testing in Latest (Develop) using IE11, FF24, CH36 for new Listing submit.

**Comment by tdressel** [comment]
Passed on Staging using Chrome 36, FF 31, IE 10
