### ISSUE TITLE
Mismatched validation error text in Submit Listing form

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-center#354]
Create a new listing with only a title and click Save. You get a validation error under Listing Type (because it is required) that says "One category is required" - it should say that the Listing Type is required.
![screen shot 2015-08-12 at 7 08 01 am](https://cloud.githubusercontent.com/assets/65660/9227040/84d2bd02-40df-11e5-9de8-cc9b1a4b9ccd.png)

**Comment by clarkjefcoat** [comment]
This issue was moved to ozone-development/ozp-react-commons#18
