### ISSUE TITLE
Add additional text to the Search Results explanations

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-center#355]
Add logic explanation words to the search results text between multiple "Types" and multiple "Organizations". Currently multiple "Categories" do this with the word *"and"* in between each multiple. 

Multiple "Types" should use the word *"or"* in between each "Type"
Multiple "Organizations" should use the word *"or"* in between each "Organization"
_Already done: Multiple "Categories" currently correctly uses the word *"and"* in between each "Category"_

CURRENT:
![image](https://cloud.githubusercontent.com/assets/8047457/9231145/8cd169f8-40f4-11e5-8bf2-b138bba6fd29.png)

**Comment by jal-vsi** [comment]
Passes testing in both Latest (develop) and Release (master) using IE11, 
![image](https://cloud.githubusercontent.com/assets/13243617/10669502/0db40a7a-78af-11e5-9e1d-a714d1a9d634.png)

**Comment by tdressel** [comment]
Sorting arrows display after column header is clicked.  They are recognizable. Passed on Staging using Chrome 36 , FF 31 and IE 10.
