### ISSUE TITLE
Settings Modal makes scrollbar disappear

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#357]
Tested on Chrome 44, Firefox 24, IE 9.  Problem exists in all browsers.

1. From Center in the dropdown menu choose "Settings"
2. In the settings modal choose "Save"
3. The scrollbar on your browser is now missing.

**Comment by jal-vsi** [comment]
Passed testing (IE11, FF24, CH36) for User, Org Steward, Admin in both environments: Latest (develop) & Release (master).  Scrollbar can be seen after choosing Save (no change save and 'Open in Webtop' save).

**Comment by tdressel** [comment]
Passed testing on HS -Staging IE10, FF, 31 and Chrome 36
Steps Used to Test-
Log into Apps Mall
Menu | Settings |  Cancel
RESULTS - Scroll bar is still available

Menu | Settings | Don't change anything | Save
RESULTS - Scroll bar is still available

Menu | Settings | Change to "Open in Webtop" | Save
RESULTS - Scroll bar is still available
