### ISSUE TITLE
Create/Edit page - Unnecessary "Could not save!" message

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#363]
1. Edit an existing approved listing
2. Scroll down to the icons section and delete one of the icons by pressing the trashcan
3. Add an icon to replace the one you just deleted by pressing "Choose File" and choosing an image file
4. Press the Save button
5. You get a "Could not save!" pop-up.

The listing changes are correctly saved, but the pop-up is confusing and wrong.

**Comment by tonyalletag** [comment]
@wski  This is still an issue in production can you take a look

**Comment by rkenyon1969** [comment]
@clarkjefcoat - tested this and could not recreate. Theory - its been resolved.

@tonyalletag

**Comment by tonyalletag** [comment]
Agreed looks like this has been fixed.

**Comment by rkenyon1969** [comment]
@tonyalletag 
@akonsowski 
@wski 

@clarkjefcoat - The issue does not occur based on the use-case above, however when doing the following the issue returned:

1. Edit an existing approved listing
2. Scroll down to the icons section and delete one of the icons by pressing the trashcan
3. Don't replace the icon you just delete
4. Press the Save button
5. You get a "Could not save!" pop-up (expected)
6. Replace the deleted icon with a new icon
7. Press the Save button
8. You get a "Could not save!" pop-up (not expected)
9. The listing is updated and saved (expected)
    - “The listing changes are correctly saved, but the pop-up is confusing and wrong.”


![scs001](https://cloud.githubusercontent.com/assets/18191566/14568280/3127541c-0306-11e6-866d-463f398e5839.png)

**Comment by rkenyon1969** [comment]
Fixed. Please use the use-case in the above thread to test.

@wski 
@akonsowski 
@clarkjefcoat

**Comment by rkenyon1969** [comment]
@clarkjefcoat - I thought I had created another bug by fixing this one, but I didn't . If you have multiple screenshots and you update one, the one you update will drop to the bottom of the list. Please confirm that this is how the page should work. - thanks!

**Comment by clarkjefcoat** [comment]
@rkenyon1969  It sounds like you have already confirmed that the reordered screenshot issue existed prior to your work on this bug.  I think you should file a new bug report about it so that we have a record of it.  I don't anticipate a fix for that issue will be at the top of anyone's list.

**Comment by rkenyon1969** [comment]
@wski 
@akonsowski 
@clarkjefcoat

Please review:

1. Edit an existing approved listing
2. Scroll down to the icons section and delete one of the icons by pressing the trashcan
3. Don't replace the icon you just delete
4. Press the Save button
5. You get a "Could not save!" pop-up (expected)
6. Replace the deleted icon with a new icon
7. Press the Save button
8. You get a "Could not save!" pop-up (not expected)
9. The listing is updated and saved (expected)

**Comment by tdressel** [comment]
Passed on latest

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Passed on Staging.
