### ISSUE TITLE
508 Compliance- Text Alternatives

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-center#370]
Provide text alternatives for any non-text content so that it can be changed into other  forms people need, such as speech.

**Comment by jal-vsi** [comment]
Text alternatives have started.  Other fixes are in work and are being resolved.  Passes initial testing in IE9/11, FF, and CH.
Ricardo will be meeting with the 508 representative to determine further requirements.

**Comment by tdressel** [comment]
Tested Nav icons, Hover over Launch and Bookmark icons and Pop up dialogue box - Launch, Bookmark, Edit and Close icons.  

Edit icons say - Unlabel for button
Close icon- says the Header of app but does not indicate it is a close icon that closes the app pop up.

**Comment by tdressel** [comment]
Passed 508 JAWS testing Nav Icons in pop up modal.
Close, Launch, Bookmark( enabled and disabled) , Edit and Tabs.

**Comment by tdressel** [comment]
CHROME - PASSED Close, Launch, Bookmark( enabled and disabled) , Edit and Tabs.
FF- PASSED Close, Launch, Bookmark( enabled and disabled) , Edit and Tabs.
IE FAILED - Bookmark and Edit buttons and Overview and Reviews tabs include extra info

**Comment by tdressel** [comment]
If we are not including IE 11 then it passes.
