### ISSUE TITLE
Submit a Listing missing data

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#375]
When creating a new listing, the last entry (Contacts) is optional.  Please add           "(optional)" to the title 'Contacts'.

**Comment by mparizernc** [comment]
Jim this may not be the case.  Contacts can be either optional or made required.  This is based on the configuration when creating a Contact Type.

**Comment by jal-vsi** [comment]
Mike, I mentioned this yesterday at the stand up meeting.  I said it seemed
to require one of two fixes.  The first is what I wrote up and the second
would be to flag it (i.e., red flag causing it to be filled in before
listing submittal) to cause it to be required.  Sounds like it is an OR
gate.  What are the 'configuration' requirements that would cause it to be
required?  I have created several listings but never ran into the situation
causing it to be required (i.e., always saved/submitted file without need
to populate Contact).

On Thu, Sep 10, 2015 at 7:31 AM, mparizernc <notifications@github.com>
wrote:

> Jim this may not be the case. Contacts can be either optional or made
> required. This is based on the configuration when creating a Contact Type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/375#issuecomment-139209474>
> .
>



-- 

Thanks,

Jim Laughter

Systems Test

Ventura Solutions Inc.

131 National Business Parkway

Suite 120

Annapolis Junction, MD 20701

(301) 623-4156

jlaughter@vsi-corp.com

**Comment by mparizernc** [comment]
If you go to Center Settings > Contact Types tab that is where it is set to be required. What should and used to happen is if you submitted the listing and they were not populated and are required an error would be thrown letting you know which ones were missing.

**Comment by jal-vsi** [comment]
Closing this issue due to the Contacts field becoming required in some cases when Admin edits it to be required.
