### ISSUE TITLE
Search area missing in IE9

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#376]
The Search box is missing in IE9.  That box is available in IE11, FF24 and CH36.
![image](https://cloud.githubusercontent.com/assets/13243617/9765428/27c07d7a-56e2-11e5-918f-10a008884cb1.png)

**Comment by clarkjefcoat** [comment]
Fixed by bhalt

**Comment by jal-vsi** [comment]
The location function is now working but the title 'Search' is not listed.  It is missing due to (E9- doesn't allow for the HTML form input element `placeholder` .. Which Center users to display the word 'search' until the user clicks the search box).  'Search' can be viewed in all other browsers (IE10/11, FF24, CH36).  Search function passes in IE9.
