### ISSUE TITLE
508 Compliance - Unlabeled Button issue in JAWS 

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-center#396]
Many un-tagged listings announcing "Unlabeled Zero Button", When tabbing through Center many instances of "Unlabeled Zero Button" and "Unlabeled Two Button.

**Comment by SOAP1914** [comment]
the 2nd part of this:
Fix the Bookmark this app button if its not bookmark

**Comment by tdressel** [comment]
Bookmarked App - "This app is bookmarked BUTTON- Bookmark"
UnBookmarked App - "Click to bookmark this app BUTTON-Bookmark"

**Comment by tdressel** [comment]
Tested on HS new staging. Chrome and FF passed
IE - Rambles through all the buttons for each pop up modal navigation button.

**Comment by tdressel** [comment]
From Pop Up Details View | Bookmarked App - Says "This app is bookmarked Button"
From Pop Up Details View | UNBookmarked App - Says " Click to bookmark this App Button"
