### ISSUE TITLE
Listing Management Table View - IE11 and Chrome when listings are filtered the rows are styled incorrectly

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#399]
When you filter on the status with a few listings the rows in IE11 and Chrome do not show correctly the rows height is more than it should be.

![10-6-2015 8-42-41 am](https://cloud.githubusercontent.com/assets/7975509/10308841/a1f25cd8-6c06-11e5-84d6-c45ccedac79e.png)

**Comment by jal-vsi** [comment]
Passed test in IE9 and CH36. Excell row/height real estate has been eliminated .
![image](https://cloud.githubusercontent.com/assets/13243617/10513004/9f28a3a0-7312-11e5-80e7-73427a58cf9f.png)

**Comment by tdressel** [comment]
Tested successfully on IE10 and 11 and Chrome as Test Admin and TestOrg Steward.
