### ISSUE TITLE
Listing Management - Org Steward Tabs do not work on first attempt

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#402]
In Listing Management the first time that you click on an Organizational tab the screen appears to update, but does not actually change the apps displayed.

If you then choose My Listings and then go back to Org tab, the results are updated as you would expect.

**Comment by jal-vsi** [comment]
Passed testing in Master (IE9/11, FF, CH).  OrgSteward1 goes to Listing Management, selects TO3 (displays 11), selects My Listing, selects TO3.  Displays TO3 (11), TO2 (18), TO (24) as expected.
