### ISSUE TITLE
Listing Management Table View - Javascript error is displayed when missing owner data

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#403]
Depending on the data loaded, you may see

Uncaught TypeError: Cannot read property 'tolowerCase' of null

in your console when loading the table view tab of some organizations in Listing Management.

**Comment by clarkjefcoat** [comment]
This is caused by Owners who have a null displayname in the database.  We do have data like that in our production environment.

**Comment by jal-vsi** [comment]
Passed testing in Master (IE9/11, FF, CH).  Admin creates draft listing (without owner org), Admin selects Menu/Listing Management, From Table View ensure Column Settings include Organization, Select Organization column and confirm draft listing is first (null Org listing).
