### ISSUE TITLE
Listing Management - Rapidly switching tabs 

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#406]
Setup:

1. Setup your test user as an Admin and as the Org Steward of multiple orgs.
2. Make it so the "All Center Listing" tab loads slowly using some combination of:
    * Have lots of listing in the Center (minimum 25).
    * Make your browser simulate a slow network (I picked "DSL" on the Chrome Network setting).

To reproduce the problem:

1. Go to the Listing Management page.
2. Chose the All Center Listing tab.
3. As soon as the numbers on the left begin to be populated, rapidly switch between multiple Org tabs.
4. When you look at the different tabs they will not be populated correctly.
5. Your browser console may have error messages.  
    * Chrome displays "Uncaught TypeError: Cannot read property 'receivePage' of undefined"
    * Firefox24 does not display an error message, it simply displays incorrect content.

**Comment by jal-vsi** [comment]
Passed testing in Master (IE9/11, FF, CH) by setting CH to DSL speed, testing in CH46 first, then using BrowserStack to check the 4 browsers.  Switching to All Center (38), then between  it and listings TO3 (10), TO2 (15), TO (10), MY (38) caused no significant delay or any error messages.

**Comment by tdressel** [comment]
Passed on Staging using Chrome 36, FF 31, IE 10
