### ISSUE TITLE
Listing Management Table View - Owner and Org sorting are broken

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#409]
In Table View, owner and org sorting are broken if the list includes a Draft that is missing an Owner or Org.

Drafts can be saved without specifying an Owner or an Org.

**Comment by jal-vsi** [comment]
Passed testing in Master (IE9/11, FF, CH). Admin creates draft listing (without owner org), Admin selects Menu/Listing Management, From Table View ensure Column Settings include Organization, Select Organization column and confirm draft listing is first (null Org listing).
