### ISSUE TITLE
User Feedback Modal

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#414]
The "X" cancel button doesn't work when a user has selected 'Read Feedback' from a listing rejected by an Org Steward.  The only option is to select 'Edit this listing', to exit.

**Comment by tonyalletag** [comment]
@tdressel Is this still an issue?

**Comment by tdressel** [comment]
1. Go to Listing Management
2. State | Needs Action
3. Choose Drop down in top right corner of app tile
4. Read Feedback
RESULTS - Feed Back pop up displays.
Edit this Listing button opened Edit Listing Form as expected.
Repeat 1-4
Choose X to cancel out of FeedBack pop up.
RESULTS - Exits out of Feedback pop up display.

**Comment by tdressel** [comment]
Passed on Staging.
