### ISSUE TITLE
Table View - export to excel

### ISSUE THREAD

**Issue by KageRyu7** [ozone-development/ozp-center#417]
A button in table view that exports the information in the table to a downloadable excel file.

**Comment by tonyalletag** [comment]
Can this button say "Export to CSV"

**Comment by jal-vsi** [comment]
The text has been changed to "Export to csv", should csv be capitalized?  

Tested in Latest using IE11, FF24, and CH36.  It fails to download the csv file in IE11 but does work in FF and CH.

**Comment by blaino** [comment]
@tonyalletag, I believe you decided that this feature does not need to be supported on IE. Please confirm.

**Comment by tonyalletag** [comment]
Confirmed - If someone ask for this we can create a new IE bug ticket

**Comment by blaino** [comment]
@tdressel, given this, can we move this one out of CI-QA?

**Comment by tdressel** [comment]
Passed in FF and Chrome on Latest using Org Steward and Admin.

**Comment by tdressel** [comment]
Passed on Staging.
