### ISSUE TITLE
What's New field does not allow 255 characters 

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#419]
Populating a Listing's field "What's New" is limited to 250, not 255 as noted.  If you delete character 251 (last 'a' shown below) it saves properly.
![image](https://cloud.githubusercontent.com/assets/13243617/10668508/96621592-78aa-11e5-8b7b-65d337a70c0c.png)

**Comment by clarkjefcoat** [comment]
The length of the what_is_new field in the database is 250.  So this is a bug with the message shown.

**Comment by akonsowski** [comment]
419: fixed what is new issue#581[https://github.com/ozone-development/ozp-center/pull/581](url)

**Comment by tdressel** [comment]
Passed on staging.
