### ISSUE TITLE
"View list of organization stewards" in 'Create New Listing' bug

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#420]
Accessing list of Org Stewards displays an unneeded vertical bar at end of Steward (yellow outline), please delete it

![image](https://cloud.githubusercontent.com/assets/13243617/10674090/344644f6-78c7-11e5-9f06-2da301107317.png)

**Comment by tonyalletag** [comment]
@tdressel is this still an issue?

**Comment by tdressel** [comment]
passed on new staging IE, Chrome and FF
