### ISSUE TITLE
Previewing listing from create/edit displays error in console.

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#422]
0. Open browser console
1. Select any listing
2. Click pencil/edit icon
3. Click eyeball/preview icon
4. Console displays: "main.js:70 Uncaught TypeError: Cannot read property 'getDOMNode' of undefined"

**Comment by tdressel** [comment]
Tested on Latest above steps and no longer error in console.  FF or Chrome.

**Comment by tdressel** [comment]
Passed on new staging IE, Chrome and FF
