### ISSUE TITLE
Eliminate warnings

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#423]
Multiple attempts to upgrade Center's React version from v12 to v13 or v14 have failed. Facebook's upgrade documentation hints that the elimination of all warnings and errors will result in a smoother upgrade. This ticket is to tamp out the warnings. 

Note that most of the warnings in Center have to do with arrays in components not having unique keys. Another common warning is the deprecation of transferPropsTo(). 

Also note that there is a known error with create/edit preview (#422).

**Comment by tdressel** [comment]
Tested on Latest - Chrome
Center | Help - Help Modal opens without error and has Help Modal content.
Center | Org Listings | Allowed user to Submit New Listing no error.

More testing pending.....

**Comment by tdressel** [comment]
More Testing on Latest - Chrome 36, FF 24 and IE11
Help Modal, Org Listings, Detailed Query ( Types, orgs and cat), Listing Tiles, Sidebar, Recent Activity Sidebar, MyListings,Overview, Details, Reviews, Resources, Administration

**Comment by tdressel** [comment]
Passed on Staging.
