### ISSUE TITLE
Require Description when rating an App

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#428]
A description should be required of > 20 characters when reviewing or rating an application in the center.

**Comment by blaino** [comment]
Requirement from Tony: character limit needs to be in the config file.

**Comment by tdressel** [comment]
Tested and passed on Chrome 36, FF 24 and IE 11.
Added and Edited Reviews with and without descriptions.  Warning if under 20 characters and allowed save if over 20 characters.
