### ISSUE TITLE
Center Makes Unnecessary API Calls

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#45]
Center makes API calls to dynamically load "type", "category", "intent", and "agency". Each API call results in a call to the security module cache followed by a call to the database cache. These services call all place demand on the API.

Loading this data from a static file would allow utilization to be disctrubuted across the content delivery tier rather than the API tier.
Could

**Comment by rpokorny** [comment]
Nish and I were talking about this yesterday, and while we agree that number of REST calls could be reduced by consolidating data, a static file solution would not work, since this data is not static.  

As far as the security plugin cache goes, that should only be getting hit at a maximum rate of once per minute per user.  Is that different from what you are seeing?

**Comment by rpokorny** [comment]
The most egregious problem with the initial REST calls has now been fixed:  The initial call to /api/profile, which would load information on every single user in the system, has been removed.  This call had been used to populate the list of available owners on the Listing create/edit form.  That list is now populated on demand using a new Profile search interface on the backend as the user types.

Additional optimizations to other calls are still possible, so I am leaving this ticket open

**Comment by mparizernc** [comment]
Verified in all the browsers the new profile search call.

**Comment by rpokorny** [comment]
Two new REST endpoints have been added in the backend: /api/metadata and /api/storefront.  Together these calls allow the frontend to get all of the information that it previously got from the following calls at page load:
/api/category
/api/type
/api/intent
/api/contactType
/api/agency
3 calls to /api/listing/search, used to populate the featured, recent, and popular listings carousels.

Further optimizations may be possible but would likely be more challenging.  @tonyalletag, is this level of optimization acceptable?

**Comment by mparizernc** [comment]
Created jmeter scripts for Metadata and Storefront and pushed them to github.
