### ISSUE TITLE
508 compliance - Fix the buttons and tabs in each app popup modal

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-center#450]
Fix the top nav in each app popup modal

**Comment by tdressel** [comment]
Should be included in 449 push.

**Comment by tdressel** [comment]
Passed in FF and CHROME.  Create bug for IE fails.

**Comment by tdressel** [comment]
In IE , it rambles on and on for the pop up modal navigation buttons.

**Comment by tdressel** [comment]
ozone-development/ozp-center#471 - Says we are no longer supporting IE for 508
