### ISSUE TITLE
508 compliance - Fix the top two carousel

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-center#461]
Fix the top two carousel, making them more accessible in JAW (so user will know they're in a carousel

**Comment by tdressel** [comment]
Now says ,"Next carousel button"

**Comment by tdressel** [comment]
IE top carousel works but second does not
Chrome - both do not work.

**Comment by tdressel** [comment]
Now says, "Heading Level 2 **Featured **and Heading Level 2 **New Arrivals**"

**Comment by tdressel** [comment]
Insert + F6
Center sidebar categories : 3
Featured : 4
new Arrivals : 4
Most Popular : 4

When I enter on any of these headers they read and navigate correctly on FF and Chrome
