### ISSUE TITLE
FF HS ONLY - Listing Type and Organizations drop downs cut off the bottom of letters

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#462]
STR-
Log onto Apps Mall using FF
RESULTS -  "g and p" in Listing Type and "g" in Organizations drop downs cut off the bottom of letters
EXPECTED RESULTS - Should not cut off.  IE and Chrome are fine.

**Comment by bhalt** [comment]
Line 48 in `node_modules/react-select-box/example/select-box.css`: line-height on '.react-select-box-label, .react-select-box-option` should be 17px (instead of 16px).

Not sure who set up the react-select-box but is this something that can be edited or do we just have to overwrite it everywhere?

**Comment by akonsowski** [comment]
i was unable to reproduce this bug either
