### ISSUE TITLE
Help Modal - Center | Search for Listings | Screenshot is squished

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#467]
STR-
Go to Apps Mall | Help Modal | Center | Search for Listings 
RESULTS - Screenshot is squished
EXPECTED RESULTS - Screen shot should be expanded to reasonable width.

**Comment by rkenyon1969** [comment]
the screenshot below is not "squished", but instead compressed more than some of the other screenshots that appear in the help topics. Do we want to standardize or leave as is?

**Comment by rkenyon1969** [comment]
![searchingtools](https://cloud.githubusercontent.com/assets/18191566/14466564/57ee708e-00a5-11e6-9e60-44ec758cb0f7.png)

**Comment by rkenyon1969** [comment]
the screenshot above is not "squished", but instead compressed more than some of the other screenshots that appear in the help topics. Do we want to standardize or leave as is?

@tonyalletag

**Comment by rkenyon1969** [comment]
@tdressel

**Comment by rkenyon1969** [comment]
the screenshot above is not "squished", but instead compressed more than some of the other screenshots that appear in the help topics. Do we want to standardize or leave as is?

@tdressel

**Comment by tdressel** [comment]
@bhalt What are your thoughts on this?

**Comment by bhalt** [comment]
leave as is .. these will eventually be replaced. @tdressel @rkenyon1969

**Comment by rkenyon1969** [comment]
thanks team. I will close this ticket.
