### ISSUE TITLE
Saving an edited listing gives error.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#469]
STR-
Go to an existing listing
Scroll down to  "screenshots" section.
Delete current pics and upload new ones
Save
RESULTS - Could not save! Your listing could not be saved because you have errors!
Expected Results - It should've saved.
Save again
RESULTS - It saves without error.

**Comment by wski** [comment]
Mine shows the error but saves anyway, the error only comes up for a brief second

**Comment by tonyalletag** [comment]
yes this is very confusing to users. They get a "did not save message" but it saves. It will cause a lot of help tickets and phone calls from our production system

**Comment by rkenyon1969** [comment]
@tdressel - when you have 5 minute can you help me re-create this bug? - thanks!

**Comment by rkenyon1969** [comment]
Can not reproduce. This may have been resolved with #363.

**Comment by tdressel** [comment]
Think Russ fixed this yesterday.  Retested and it behaved the way it should.
