### ISSUE TITLE
Metrics reporting search query's should not be case sensitive

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#470]
investigate if we can lowercase all search queries prior to executing them so that our metrics don't report users searching on both "MAp" "map" and/or "MAP" as different queries.

**Comment by tdressel** [comment]
On hold for testing until communication between Latest to Metrics server is established.

**Comment by tdressel** [comment]
I as unable to access metrics.  Not sure why yet but Soe was able to verify for me that results were returning with UPPERCASE, lowercase and Both in IE10, CHROME and FF.
