### ISSUE TITLE
508 IE Only - Bookmark and Edit Buttons, Overview and Reviews tabs include extra info.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#471]
STR-
Launch IE 11
Launch JAWS
Go to https://ci-latest.amlng.di2e.net:7799/center/#/home
Tab to an App to generate the pop up modal
Tab through pop up modal
RESULTS - Bookmark Button, Edit Button, Overview Tab and Reviews Tab say more than it should.
EXPECTED RESULTS - Those two buttons and two tabs should only say the information about their functions.

**Comment by tonyalletag** [comment]
@SOAP1914 @tdressel Suggest closing if we are not looking to support 508 for IE

**Comment by tdressel** [comment]
Not supporting IE for 508.

**Comment by tdressel** [comment]
Closing if not supporting for IE
