### ISSUE TITLE
Search - Repeated Searches

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#473]
Repeating a search after going to a different page does not work.

1.  Go main page type "test" into search box.
2.  From the hamburger menu choose "Listing Management"
3.  Return to the main page by clicking the shopping bag icon in the top menu bar.
4.  Type "test" into the search bar.

Expected Result:  Search results are displayed.

Actual Result:  The word "Searching..." is displayed on your screen forever (This is an estimate, I waited 30 seconds).

**Comment by wski** [comment]
Can this be moved to resolved? @clarkjefcoat

**Comment by tdressel** [comment]
Passed on Latest.  IE, FF and Chrome

**Comment by tdressel** [comment]
Passed on new staging. IE, Chrome and FF
