### ISSUE TITLE
Double-scrollbar on Create Edit Page (Chrome, Firefox on Ubuntu)

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#479]
On the new-backend branch (CI-Prototype), there is double-scrollbar on the Create Edit Page when viewed in Chrome and Firefox on Ubuntu. Note that this does not happen in Chrome or Firefox on the Mac. It is currently unknown whether or not the problem exists on IE.

**Comment by tdressel** [comment]
Passed on new Staging IE, FF and Chrome.
