### ISSUE TITLE
Saving an image to a Listing causes a 500 Internal Error

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#481]
@blaino @arw180 

STR-
Go to https://ci-prototype.amlng.di2e.net/center/
Submit a Listing
Fill out Listing ( Security Markings, Name, Listing Type and Image with Security Markings) 
Save
RESULTS - Uploading images hangs.  Dev Tools gives "500 Internal Error".
EXPECTED RESULTS - Should save without hanging.

**Comment by blaino** [comment]
@tdressel , I've tried to replicate, but I can't. Please try again.

**Comment by tdressel** [comment]
Duplicate - 487 and 488
