### ISSUE TITLE
When file exceeds size limit it continuously spins 

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#488]
STR-
Go to Submit a Listing
Upload an image that exceeds the size limit
Save
RESULTS - 500 Internal Error in dev console. App just spins as if it is saving forever.
EXPECTED RESULTS - Should give user an error that the file size has exceeded the limit.

**Comment by blaino** [comment]
Resolved by fix to #487

**Comment by tdressel** [comment]
Now gives an error.

**Comment by tdressel** [comment]
Now gives a user friendly error. Tested IE, FF and CHROME.
