### ISSUE TITLE
Investigate removal of libraries support for foreign langauges

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#49]
Investigate removal of foreign langauge libraries.  If its easy remove them. If its hard probably not a big deal.

**Comment by clarkjefcoat** [comment]
I believe this is in reference to many of the files in the locale directories of the moment and w2ui libraries.

**Comment by nishp1** [comment]
They get downloaded into node_modules as part of the libraries since they support internationalization, but they don't get bundled into the final output as we haven't enabled its usage.

**Comment by nishp1** [comment]
@tonyalletag @mparizernc can we close this if foreign language files are not in final build?

**Comment by tonyalletag** [comment]
@nishp1 Yes, that was the concern. that someone scanning the code would see foreign langauges and cause us more problems and effort then it would be to remove it.
If it is significant effort to remove them, we can continue to explain why they are there.

**Comment by nishp1** [comment]
Yeah, we are handling dates though `moment` and admin grid/list views with `w2ui` replacing both isn't easy let's say.

Shouldn't scanning be done on final build?

**Comment by tonyalletag** [comment]
This is not an issues
