### ISSUE TITLE
Clicking the "x" on an empty search box in Center replaces tiles with "Searching..."

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-center#490]
Steps: 
Go to Center
Click a category on the left (wait for listing tiles to show)
Click the "x" on the search box (even though there are no search terms in it)

Result: 
Listing tiles disappear and "Searching..." text shows forever

Expected Result:
Nothing should happen because there were no search terms to remove

Browser: Chrome
Login: bethany

**Comment by clarkjefcoat** [comment]
Currently: 
1.  Select a Category
2.  Select a "Listing Type" or "Organization"
3.  Type something in the Search Box
4.  When you click the 'x' in the search box, the "Listing Type" and "Organization" fields are cleared (in addition to the search box being cleared).  The Category remains.

If you repeat these steps without step 3, I think the "Listing Type" and "Organization" should still be cleared to be consistent.
1.  Select a Category
2.  Select a "Listing Type" or "Organization"
3.  Do nothing.
4.  When you click the 'x' in the search box, the "Listing Type" and "Organization" fields are cleared.  The Category remains.

Is this how we should handle both scenarios or should we do something different?

**Comment by bhalt** [comment]
I didn't realize that was the current functionality and not sure that I agree. Because it was designed with an "x" for each field (search term, listing type, and org), the "x" click on each field should only clear that specific field. This isn't the current functionality but was how it was originally designed. If the "x" applies to more than the box it is in, it probably shouldn't be in a box. Thoughts @clarkjefcoat?

If we need a "clear all" click, that's maybe something we could add after the description text that appears after a filter/search selection of any kind (i.e. the current text "Search Results for listings matching a with the type web application in the organization Minitrue")

**Comment by clarkjefcoat** [comment]
I wanted to keep any updates consistent.  If the 'x' should only apply to the search box then we need to add another ticket to fix the current functionality.  That would be fine with me.

I don't think we should add a "clear all" click now.

**Comment by tdressel** [comment]
Passed in Latest.

**Comment by tdressel** [comment]
PAssed on staging.
