### ISSUE TITLE
Inconsistent error message when upload icon/banner/screenshots exceed 1 MB

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#494]
Go to Listing
Edit
Upload a png, jpg or gif that exceeds 1MB.
Save
RESULTS - Error saving.  Upload has exceeded 1 MiB
EXPECTED RESULTS - Should say,"Error saving.  Upload has exceeded 1 MB" NOT MiB

**Comment by akonsowski** [comment]
Unable to reproduce this issue. Text reads 1MB.
![selection_003](https://cloud.githubusercontent.com/assets/18122042/14363556/e0029d3c-fcd2-11e5-986f-9617edadbbae.png)

**Comment by tdressel** [comment]
Passed on staging.
