### ISSUE TITLE
Warn users with unsupported browsers

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#495]
Mostly for users with older versions of IE - Pop up a warning message that says what browsers we support and tell them to try to access the site using one of them.

**Comment by tonyalletag** [comment]
Detect what browser the users is using if the users is not using one of the browsers listed below popup a warning message. If they are using a version of IE below 10 don't allow them to access the site

Message should say 
OZP is test against the following browsers:
IE 11 +
FireFox 24+
Chrome 36+

**Comment by wski** [comment]
Blocking the user completely can be done but would leave them confused, instead I've redirected them to https://browser-update.org/update.html which provides links to updated browsers. This of course will not work if the user has no external connectivity, However the link can be easily changed to some existing documentation within that infrastructure. There is also the option to create a react route that simply says "to access this page please update your browser" however if their browser really sucks they might not be able to access this page either.

**Comment by tonyalletag** [comment]
This should include a sweet alert - text should say
"
This site is tested against the following browsers:
IE 11 +
FireFox 24+
Chrome 36+
We have detected that you are using an unsupported browser and some features may not function as expected

"
