### ISSUE TITLE
undefined continuously displays across top of Returned Listing 

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#501]
STR-
Go to Listing Management | All Center Listing | Table View
Delete an app using the trashcan icon in last Actions column
Change State to Draft 
Change State to Returned
RESULTS - undefinedundefinedundefinedundefined continuously displays across the top.
EXPECTED RESULTS - this should not display.
Happens on all browsers.

**Comment by wski** [comment]
After deleting the app there is no way to change the state to Draft or Returned, since the app is gone.

**Comment by tdressel** [comment]
Repro'ed using steps above.  After you delete an app you change the state from "All" to "Drafts".  I could not repro on Lowside but will revisit on high side.

**Comment by tdressel** [comment]
Looked good on Highside.
