### ISSUE TITLE
Tour: Hitting previous from quickview ends tour unexpectedly 

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#504]

**Comment by tdressel** [comment]
Passed on latest

**Comment by tdressel** [comment]
FF Fails on Staging.  Previous button doesnt advance past Listing Tiles

**Comment by akonsowski** [comment]
#614 should fix this bug. i just tested it out and it looks like it works.

**Comment by tdressel** [comment]
Passed on Staging.
