### ISSUE TITLE
Private Listing option is blocking listing from org steward level.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#509]
STR-
Log on as aaronson (miniluv)
Submit a Listing with Private Listing Setting enabled.
Save and Publish
Log on as julia (miniluv) org steward
Go to All Listings / Ministry of Love Listings
RESULTS - Can't see aaronson's listing he just submitted.
EXPECTED RESULTS - Should be able to see listing submissions that are submitted by users in miniluv org. Org Stewards and Admins should be able to see everything pertaining to org in order to approve. The admins can see aaronson's private listing.

**Comment by wski** [comment]
#74 fixes this, but I needed to click "Ministry of Love"s listings in listing management before "needs action" showed up in the sidebar.

**Comment by tonyalletag** [comment]
ready for testing

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Private Listing is disabled for now.
