### ISSUE TITLE
Infinite scroll search, and most popular (until all results displayed) 

### ISSUE THREAD

**Issue by wski** [ozone-development/ozp-center#510]

**Comment by wski** [comment]
fixed in #511

**Comment by tdressel** [comment]
Steps used to test:
logged into apps mall as admin
Searched on known app
While it was searching I tried to scroll "infinitely" but did not scroll
Results displayed and looked fine. 
PASSED.

**Comment by tdressel** [comment]
Passed on new staging.  IE, Chrome and FF
