### ISSUE TITLE
IE: App listing requires three or more mouse clicks to open App Modal

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#512]
Internet explorer only:

On the center homepage scroll to the bottom 
click on an app listing
nothing happens
click on it a few more times eventually the app modal will open

**Comment by tonyalletag** [comment]
This no longer seems to be an issue on staging with the new backend and infinite scroll

**Comment by tdressel** [comment]
Couldnt repro this on IE Latest. Passed

**Comment by tdressel** [comment]
Passed on IE11
