### ISSUE TITLE
bower.json file removed from center-ui but instructions still say to build with bower

### ISSUE THREAD

**Issue by david-t-daniel** [ozone-development/ozp-center#516]
Is it possible to get either the new build command or if bower.json was removed by accident then can that be recovered.

**Comment by david-t-daniel** [comment]
Ok I see that it was removed on purpose in commit e2c1b2f1908edcde3ccf7aaae49c2a8991d6b61b  I will search on the current way to build.

**Comment by clarkjefcoat** [comment]
@david-t-daniel - Thanks for the filing the issue.  I've updated the README.md to remove references to bower.  We are now doing all of our javascript dependency management with npm.

For the build, no additional steps are necessary.  The change is that you no longer need to run the bower install.
