### ISSUE TITLE
Submit a Listing hangs on Uploading images when saved.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#523]
Add a Listing
After adding all images 
Submit Listing.
RESULTS - Hangs on Uploading images
EXPECTED RESULTS - Should not hang.

**Comment by clarkjefcoat** [comment]
This is a center issue after all.

**Comment by clarkjefcoat** [comment]
Please re-test.

**Comment by tdressel** [comment]
Passed on staging.
