### ISSUE TITLE
Bookmark and Unbookmark doesnt toggle.  

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#525]
STR-
Go to an app in IE
Choose Bookmark 
It doesn't toggle back and forth.
RESULTS - Should highlight and unhighlight.

**Comment by wski** [comment]
Please specify IE version

**Comment by clarkjefcoat** [comment]
Cannot reproduce.

Can you show this to me on the staging environment?

**Comment by tonyalletag** [comment]
I reproduced this bug on staging with IE10.  I could bookmark an app but I could not unbookmark it.

**Comment by tdressel** [comment]
This also works in IE on HS.
