### ISSUE TITLE
Help | Doesn't open Help Tour

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#526]
STR
Go to Homepage using IE browser
Help Modal
Take the Tour button
RESULTS - Nothing
EXPECTED RESULTS - Should launch tour.

**Comment by wski** [comment]
Please specify IE version

**Comment by clarkjefcoat** [comment]
Cannot reproduce.

Can you show this to me on the staging environment?

**Comment by tonyalletag** [comment]
Could not reproduce in staging with IE10

**Comment by tdressel** [comment]
This works now.  Tested on HS.
