### ISSUE TITLE
Help Modal abruptly stops with overlay 

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#529]
STR-
Go to AppsMall Center
Help icon
Take the Tour
RESULTS - Help Tour starts on HUD located on navigation bar
Advance through to the Tour until the pop up modal displays
RESULTS - FF stops the overlay immediately but user is able to navigate using the arrows but it eventually stops responding.  Chrome it stops loading the overlay for Overview Tab, then resumes on Reviews, Details, Resources and then it stops.
EXPECTED RESULTS - Should advance til the end.  At the end there should be something telling the user it is ending the tour.

**Comment by clarkjefcoat** [comment]
This happens on FF 31.5

**Comment by tdressel** [comment]
Both FF and Chrome advance properly and the NEXT button was removed from the last step in tour.

**Comment by tdressel** [comment]
Passed on Staging.
