### ISSUE TITLE
App Details pop up with multiple screenshots display the left scroll bar out of alignment.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#531]
STR-
Go to Adv App
Open Pop Up Details
RESULTS - Left Scroll bar is not aligned properly
EXPECTED RESULTS - Should be aligned properly.

**Comment by clarkjefcoat** [comment]
![multiplescreenshots](https://cloud.githubusercontent.com/assets/7015118/13748164/0f6ae264-e9d2-11e5-8725-ebf6c981aaa6.png)

When you have multiple screenshots, the left carousel bar is misaligned.

**Comment by bhalt** [comment]
This is an issue of the carousel in the modal taking on the custom positioning of the carousel in the main Center screen.

@wski to fix, you can add 

```.modal .carousel-wrapper .prev { left: 0px; }``` 

to https://github.com/ozone-development/ozp-center/blob/master/app/styles/_carousel.scss -thanks!

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
Passed on staging.
