### ISSUE TITLE
Notifications - Redo UI and Modal

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#535]
A user remarked that the scrollbar for notifications can be easily overlooked.  Especially if the underlying featured app has a white/gray color scheme.

![notificationscroll](https://cloud.githubusercontent.com/assets/7015118/13752470/2d871f2a-e9e5-11e5-9c01-e6080f2bb701.png)

**Comment by bhalt** [comment]
Haven't seen this often but definitely agree that it isn't ideal. Changing the color scheme for just that scrollbar (esp with browser differences) could be a nightmare though. Best option if we want to go that route would probably be a plugin. 

Do we really need a scrollbar? Maybe there isn't a max height on that for now? Or overflow "See more" could be put into a Notification modal where they can manage all notifications? Not sure how many notifications people are getting, how long they are staying, or what's realistic. Would be a good topic for more discussion.

**Comment by bhalt** [comment]
Couple ideas for implementation after sprint discussion: @tonyalletag 

Rework the notification dropdown to allow more real estate for displaying longer text fields. Also remove the max-height/scrollbar and direct to a Notification modal to see more:
![notifications_expanded](https://cloud.githubusercontent.com/assets/8047457/13826523/6e8f1162-eb8e-11e5-8a65-ea57b4557e48.PNG)

Create a notification modal to display more notifications as well as complete text. Also allow for a "more information" button link (or just allow <a> tags within the notification text).
![notifications_expanded_modal](https://cloud.githubusercontent.com/assets/8047457/13826522/6e8e789c-eb8e-11e5-9683-bceb3e167feb.PNG)

**Comment by tonyalletag** [comment]
@bhalt Both of these are good options. 
I could see either of these working. I will ask our content stewards to provide feedback.

**Comment by pskalski** [comment]
Tony, Bethany -- either works for me! My main interest is having more notification space to provide more description. Thanks for addressing this!

**Comment by bhalt** [comment]
@tonyalletag these were actually designed to work in tangent. Still not sure I have all the use cases, but if we foresee users having more notifications than can be seen on the initial dropdown, I'd suggest having a notification modal as the command center to look through all of them.

**Comment by tonyalletag** [comment]
First addressed in #457

**Comment by wski** [comment]
Can you outline what the filters are other than Date? I understand the rest

**Comment by bhalt** [comment]
Hmm. Would be neat to have an "importance" filter (AML platform notifications, then Org notifications, then app notifications by date). If that's too hard of an algorithm we can just show the Filter now, remove the Sort, and just default sort by date. @wski

**Comment by wski** [comment]
Sounds good, will investigate importance

**Comment by wski** [comment]
I've gone ahead and put the sorting on the back burner for now, I think we should do that when peer 2 peer notifications and app notifications are implemented, but not right now.

**Comment by wski** [comment]
What is "more information" supposed to show?

**Comment by bhalt** [comment]
@wski the plan was to expand the notification data to allow for more text (very limited number of characters now) and the option of adding links (buttons), viewed from the modal

**Comment by tdressel** [comment]
The notifications now expand and when user chooses "See more" a notification modal displays with all of the notifications to choose from.

**Comment by pskalski** [comment]
Thanks Tiff....and the hyperlinking is appreciated as well!

**Comment by tdressel** [comment]
Passed on staging.
