### ISSUE TITLE
Remove redirects

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#539]
The python backend is sending redirects (HTTP Status 301) when you connect to a URL without a trailing slash.  It redirects to the same URL with a trailing slash added.

Can/should we fix this by adding trailing slashing to URL requests?

**Comment by clarkjefcoat** [comment]
The /category and /contact_type endpoints have this same problem.

**Comment by clarkjefcoat** [comment]
Also /search

**Comment by tonyalletag** [comment]
@skhtet @mannyrivera2010 Lets discuss this one

**Comment by tdressel** [comment]
Passed on latest.
