### ISSUE TITLE
Search and Discovery Page - Make the Types filter on the left side into a drop down at top right

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#54]
See mockups in JIRA OZF-668

**Comment by sdeighan** [comment]
![o3_searchanddiscovery](https://cloud.githubusercontent.com/assets/7987446/6288412/d881eabc-b8e6-11e4-848e-89c71c1a692d.png)

**Comment by nishp1** [comment]
@sdeighan pushed both dropdowns to branch `discovery-dropdowns`. Feel free to review and work on CSS.

**Comment by nishp1** [comment]
@sdeighan `open` class is added now to drop downs.

**Comment by mparizernc** [comment]
All Browsers

The filters have been verified and all outstanding bugs have been captured in bug tickets.
