### ISSUE TITLE
Listing - Viewing Reviews for a Listing creates two duplicate calls to backend  

### ISSUE THREAD

**Issue by mannyrivera2010** [ozone-development/ozp-center#546]
Viewing Reviews for a Listing creates two duplicate calls to Backend  

![image](https://cloud.githubusercontent.com/assets/1072762/13828086/1fa3ab82-eb96-11e5-914c-218735a224cc.png)

**Comment by wski** [comment]
@akonsowski is this what you were working on the other day?

**Comment by wski** [comment]
So the reason this happens is because of the component will receive props, in the case that you're not transitioning to another application it hits the backend twice, but this should only happen the first time.

**Comment by wski** [comment]
On second thought I believe the issue is that the reviews tab is calling componentWillMount twice, so somehow we're mounting two reviews tabs.

**Comment by akonsowski** [comment]
it looks like the will receive props and will mount are getting called at the same time.

**Comment by tdressel** [comment]
Test with Bug fix 656

**Comment by tdressel** [comment]
Test on staging and only saw one call.  Passed.
