### ISSUE TITLE
Submit Listing | Changing contact type on Submit Listing form doesn't save.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#547]
STR-
Submit a Listing
Add two contacts with same contact type 
Save Draft
Scroll down and change the contact type to something else
Save Draft
RESULTS - Contact Type doesnt change.
EXPECTED RESULTS - Contact type should save change

**Comment by clarkjefcoat** [comment]
Issue moved to [ozone-development/ozp-backend #118](https://github.com/ozone-development/ozp-backend/issues/118) via [**ZenHub.io**](https://www.zenhub.io/)
