### ISSUE TITLE
Search and Discovery Page - Make the Organizations filter on the left side into a drop down at top right

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#55]
See mockups in OZF-668

Organizations should be displayed by their shortname

**Comment by sdeighan** [comment]
![o3_searchanddiscovery](https://cloud.githubusercontent.com/assets/7987446/6288518/a54bb80c-b8e7-11e4-95ea-6b424c6ab2ec.png)

**Comment by nishp1** [comment]
What does clicking on links Featured, New Arrivals and Most popular do?

**Comment by sdeighan** [comment]
They would take you to a page filtered to just include listings available in the carousels. Those are Post-IOB unless we have lots of extra time on our hands

**Comment by mparizernc** [comment]
All Browsers

The filters have been verified and all outstanding bugs have been captured in bug tickets.
