### ISSUE TITLE
Quickview Modal - Admin tab should show errors if change not possible

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#557]
As of the writing of this ticket this issue can be see on ci-release:
1.  Search for JotSpot
2.  Click on JotSpot to get the QuickView modal
3.  Click on the Admin tab
4.  Attempt to change the "Enabled" or "Featured" slider

You will note that the slider does not change.  Check your browser console.  You will see that the put call returned error messages.

Add a pop-up to display those error messages to the user.  Something like:  "This listing must be updated to fix the following errors before changes can be made:"  and then the list of the errors.

**Comment by tdressel** [comment]
Passed on Latest. No longer see these errors in console.  The toggle saves.

**Comment by tdressel** [comment]
Passed on staging.
