### ISSUE TITLE
Center Settings - Scrolling to bottom of page breaks infinite scroll

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#559]
1.  Login as an admin
2.  Go to the main Center page
3.  From the menu choose "Center Settings"
4.  On the resulting page scroll to the bottom.

In your console you will see a error "Invariant Violation: replaceState..."

5.  Click the Shopping Bag to go back to Center.
6.  Scroll to the bottom of the page.

Infinite Scroll is now broken.

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Passed on staging.
