### ISSUE TITLE
IE ONLY- Star reviews display lines in between the stars

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#562]
STR
Drill into an app
Reviews Tab
RESULTS - Stars display with lines in between them
EXPECTED RESULTS - Should be consistent with FF and Chrome.

**Comment by akonsowski** [comment]
fixed with PR 562 in ozp-icons

**Comment by tdressel** [comment]
Passed on latest - IE, Chrome and FF

**Comment by tdressel** [comment]
Passed on staging.
