### ISSUE TITLE
Delete Review doesn't delete the review from the left side Average Rating Section

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#563]
STR-
Add a review to an app.
Delete the review.
Click through the "are you sure?" prompt.
RESULTS - Review is removed from User Review and Review this Listing Section but stays in Average Rating Section
EXPECTED RESULTS - Should be removed from all sections and not require a refresh in order to clear out the review.

**Comment by rkenyon1969** [comment]
Can't recreate bug with latest version of "git pull" for master. I believe this issue was resolved thanks to:

491: fixed IconRating issue 

@tonyalletag 
@tdressel

**Comment by rkenyon1969** [comment]
@clarkjefcoat

**Comment by clarkjefcoat** [comment]
Looks resolved to me too (Tested in Chrome, IE11)

**Comment by tdressel** [comment]
Passed

**Comment by tdressel** [comment]
Passed on Staging.
