### ISSUE TITLE
Metrics Link in common toolbar should be visible to Org Stewards and AppsMall Admins

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#566]
Currently Org Stewards do not see a link to metrics

**Comment by tdressel** [comment]
What unable to reproduce this on Latest.
Logged in as org steward
Verified in HUD, Center and WebTop the Metrics link in the Menu drop down DOES exist.

Logged in as basic user
Verified in HUD, Center and WebTop the Metrics link in the Menu drop down DOES NOT exist.
