### ISSUE TITLE
Quickview Modal - Admin tab contains extra "modified" record

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#568]
After a user submits a listing, the Quickview Administration tab contains:

![modifiedsubmitted](https://cloud.githubusercontent.com/assets/7015118/14045742/06b12904-f273-11e5-895b-853d22d1f5b0.png)

There is no need for the "modified" line.  This differs from how the old system recoreded changes.

**Comment by akonsowski** [comment]
Issue moved to [ozone-development/ozp-backend #140](https://github.com/ozone-development/ozp-backend/issues/140) via [**ZenHub.io**](https://www.zenhub.io/)
