### ISSUE TITLE
Create/Edit Page - Add expanding tabs navigation into left column

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#57]
See mockups in OZF-678 

Each item in the tabs should act as an anchor tab in essence taking the user to the label/link selected.  Tab headers should take you to Section headings and field links should take the user to the fields.

**Comment by sdeighan** [comment]
![mp_createeditform_details](https://cloud.githubusercontent.com/assets/7987446/6288400/b9444e4c-b8e6-11e4-9a16-53bbb1c31265.png)
![mp_createeditform](https://cloud.githubusercontent.com/assets/7987446/6288399/b940d726-b8e6-11e4-9e07-421852818d37.png)

**Comment by sdeighan** [comment]
UX Review complete ^_^

**Comment by rpokorny** [comment]
Resolved in create-edit-3-col branch

**Comment by mparizernc** [comment]
All Browsers

Verified the multi-tab functionality of the create/edit page.
