### ISSUE TITLE
FIREFOX and CHrome ONLY- Thin black box displays around screenshots and rating descriptions

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#572]
STR-
Go to an app with several screen shots
Open Pop Up Details
Scroll through the screenshots
RESULTS - An awkward thin black/blue box displays around the screen shots and description
EXPECTED RESULTS - Shouldn't display this thin black/blue box

Also happens when adding a rating description via popup details window.

**Comment by tdressel** [comment]
<img width="897" alt="screen shot 2016-03-28 at 4 24 52 pm" src="https://cloud.githubusercontent.com/assets/5015370/14089243/f3b90aba-f501-11e5-8fe8-5a78c861b5e5.png">

**Comment by rkenyon1969** [comment]
Matt - I've determined this can be resolved by adding a css attribute of outline:none to the * {} class in /dist/assets/main-blessed1.css. Could you walk me through how to modify/update that file? - thanks

@wski 
@tdressel 
@clarkjefcoat 
@akonsowski

**Comment by wski** [comment]
This will fix it, however we should find out the root cause of our containers having this outline on `:active`. It's also important to note that adding the wildcard will remove it for elements where it should stay for accessibility reasons, such as input fields, textareas, buttons, etc.

**Comment by rkenyon1969** [comment]
Agreed. My working theory is that the border is appearing because of the tabindex on the given element. In this case it is the <div> tag that make up the main sections of the "Overview" tab:

<div class="tab-pane active row quickview-overview" tabindex="0" data-reactid=".0.1.0.0.1.$tabs-container.1.0">

Question: (per Matt's point above) is this a 508 requirement or can we remove with either *{} or [tabindex]{} or on each individual element?

**Comment by rkenyon1969** [comment]
@SOAP1914 - can you review to see if this needs a 508 review/input? - thanks!

**Comment by rkenyon1969** [comment]
Ricardo has signed off that the border is not a 508 requirement and can be hidden. I will fix by applying above solution:

"I've determined this can be resolved by adding a css attribute of outline:none to the * {}"

**Comment by rkenyon1969** [comment]
[tabindex] {
   outline: none !important;
}

[tabindex][input] {
   outline: 'default';
}

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on Staging.
