### ISSUE TITLE
Listing Management - Recent Activity should show icons

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#587]
A previous version of the Recent Activity tab displayed application icons next to the entries.  A request has been made to restore those icons.

**Comment by rkenyon1969** [comment]
Currently, changeLog.Listing.iconUrl not present. Need to add small_icon to ShortListingSerializer in ozp-backend to pull icon URL into changeLog.Listing.

**Comment by rkenyon1969** [comment]
Per Manny's work in backend, I update code in center and tested using backend branch #156.

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Passed on Staging.  Shows the small icon.
