### ISSUE TITLE
Create/Edit Page - Invalid portion markings are allowed

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#588]
Find an existing app
Edit Listing
Carefully select the second to last letter of the Security Marking and select all previous letters.
Using keyboard, type HELLO

This should not be allowed.  The only way to enter a classification should be by using the bootstrap-classify pop-up that appears when you click in the portion marking box.

**Comment by rkenyon1969** [comment]
@clarkjefcoat 
@wski 

Please review and test.

**Comment by tdressel** [comment]
Passed on Latest. Can no longer type in the classification fields.

**Comment by tdressel** [comment]
Passed on Staging.
