### ISSUE TITLE
Listing: Administration Tab: Bookmark icon no change unless page refresh

### ISSUE THREAD

**Issue by rkenyon1969** [ozone-development/ozp-center#596]
see ozone-development/ozp-backend/#154

**Comment by rkenyon1969** [comment]
https://github.com/ozone-development/ozp-backend/issues/154

**Comment by rkenyon1969** [comment]
@mannyrivera2010 - FYI

**Comment by clarkjefcoat** [comment]
Copying helpful screenshots from backend ticket:


The UI is not changing states of icons which makes it possible to bookmark an app again when the app was enabled again. 
![image](https://cloud.githubusercontent.com/assets/1072762/14798259/ab541a62-0b04-11e6-9585-3849f62d2998.png)
**After Enabling app**
![image](https://cloud.githubusercontent.com/assets/1072762/14798329/19409a6e-0b05-11e6-9e52-e933cf38a36c.png)

**Comment by rkenyon1969** [comment]
see https://github.com/ozone-development/ozp-backend/issues/159

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on Staging.
