### ISSUE TITLE
Launching a Listing - Launching a listing in Center that is not bookmarked should bookmark the listing if launching into webtop

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#60]
Currently if the default launch method is set to webtop and a user launches a listing from the center it will open the listing in the webtop but IWC is unaware of it so it does not work. We need to bookmark the listing before launching it into webtop.

**Comment by rpokorny** [comment]
@mparizernc : ready for testing

**Comment by mparizernc** [comment]
All Browsers

I have verified that launching a listing from the center when the default launch preference is webtop, bookmarks the listing and then launches it into the webtop, However this does require the user to accept popups for that site.  I also verified the behavior of the HUD and the center when the default is tab.

**Comment by rpokorny** [comment]
I haven't seen a popup warning while I was developing... I would consider that to be an issue.

**Comment by rpokorny** [comment]
Awaiting decision from customer about popup blocking

**Comment by rpokorny** [comment]
It has been decided that Center will not support launching into Webtop at all.  The Launch button in Center will always open the listing in a new tab. Working on this now...

**Comment by mparizernc** [comment]
All Browsers

Verified that the center launches listings into a new tab regardless of what is set in the user's settings.  I also verified that the hud still works properly.
