### ISSUE TITLE
Add Listing DELETED to Activity Log and Listing Modal

### ISSUE THREAD

**Issue by mannyrivera2010** [ozone-development/ozp-center#602]
This issue is for the front-end changes require for https://github.com/ozone-development/ozp-backend/issues/48

**Comment by tdressel** [comment]
Displays as deleted in Listing Management | All Center Listings | List View
Displays as deleted in Listing Management | My Listings  Drill into pop up modal | Admin tab

**Comment by tdressel** [comment]
Passed on staging.  When an app is deleted it is logged in the Recent Activity with username and on All Center Listings and My Listings as deleted.
