### ISSUE TITLE
Add links for deleted apps in recent activity

### ISSUE THREAD

**Issue by akonsowski** [ozone-development/ozp-center#619]
recent activity  needs links to all listings

**Comment by wski** [comment]
Is this still an issue?

**Comment by tdressel** [comment]
Recent Activity displays -
Recent Activity

3 minutes ago
Big Brother deleted JotSpot 9 (Deleted)

**Comment by tdressel** [comment]
Tested on HS and requires a refresh like all actions. I think it would be super cool if it did not require refesh
