### ISSUE TITLE
Notifications Menu - Closes when any notification is dismissed

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#62]
When you click "dismiss" on any notification, the dropdown menu closes. The dropdown menu should stay open until the dropdown is closed or the user clicks off the menu.

**Comment by nishp1** [comment]
This *should* be fixed once #94 is.

**Comment by stephanieerin** [comment]
temp-master

**Comment by mparizernc** [comment]
All Browsers

Verified that I am able to close a notification in both HUD and Center and the rest of the notification list does not close on me.
