### ISSUE TITLE
deleted apps should have an icon that shows they are deleted

### ISSUE THREAD

**Issue by akonsowski** [ozone-development/ozp-center#620]
when apps are deleted they will show up with a / and will be unclickable under listing management all listings
![image](https://cloud.githubusercontent.com/assets/18122042/15254855/ed443906-1906-11e6-9558-2658cdc23bb5.png)

**Comment by wski** [comment]
Is this still an issue?

**Comment by tdressel** [comment]
Passed on Latest.  Icons in Listing Management display properly.  Deleted Apps are removed from Center Homepage.

**Comment by tdressel** [comment]
Passed on Staging.
