### ISSUE TITLE
notification module displays notification's date wrong

### ISSUE THREAD

**Issue by dylankolson** [ozone-development/ozp-center#625]
Date is off by a month. For this example it should show May not June.

![screen shot 2016-05-18 at 11 31 12 am](https://cloud.githubusercontent.com/assets/10820108/15364897/2f69db4a-1cec-11e6-81fd-6aa528fa1ce3.png)

**Comment by clarkjefcoat** [comment]
@dylankolson - Thanks for the bug report and the fix.  

But please don't close Issues for us.  We like for issues to remain open until they are closed by one of our testers.

**Comment by tdressel** [comment]
Date displays accurately on latest.  Tested with expiration date in May and June and both worked.
