### ISSUE TITLE
Build - gulp task needed to set shrinkwrap versions of internal dependencies

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#634]
When creating an npm-shrinkwrap.json file we should always use the latest release available for internal dependencies.

**Comment by akonsowski** [comment]
@mannyrivera2010 is this done with the script to automate the builds?

**Comment by mannyrivera2010** [comment]
This is being automated with release process automation script

**Comment by mannyrivera2010** [comment]
Issue moved to [ozone-development/dev-tools #23](https://github.com/ozone-development/dev-tools/issues/23) via [**ZenHub**](https://www.zenhub.com/)
