### ISSUE TITLE
404 error when saving new categories 

### ISSUE THREAD

**Issue by akonsowski** [ozone-development/ozp-center#641]
![image](https://cloud.githubusercontent.com/assets/18122042/15712516/90908168-27e0-11e6-8cfe-2585ae92efea.png)

**Comment by tdressel** [comment]
I was able to save a new CATegory without any issues.
Verified the category was available in Submit Listing form and on Center homepage.  Also tested category search filters with new category.

**Comment by tdressel** [comment]
Passed on Staging
