### ISSUE TITLE
Fix(Bookmark): str.includes() method not backward compatible 

### ISSUE THREAD

**Issue by rkenyon1969** [ozone-development/ozp-center#649]
JavaScript method str.includes() not supported in older versions of approved/used browsers on high-side:

IE 11 - not supported
Firefox (24-39) - not supported 
Chrome (36-40) - not supported

* based on tests of all three browsers on browserstack.com

Latest Versions:
IE 11
Firefox 47
Chrome 51

**Comment by rkenyon1969** [comment]
Solution based on Matt and Clark's suggestion:

if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';
    if (typeof start !== 'number') {
      start = 0;
    }

    if (start + search.length > this.length) {
      return false;
    } else {
      return this.indexOf(search, start) !== -1;
    }
  };
}

**Comment by tdressel** [comment]
Passed on Staging.
