### ISSUE TITLE
Disabled and Enabling duplicated apps in hud folder.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#658]
STR-
Submit a Listing
Bookmark it
Go to HUD
Add it to a folder
Open folder and Get Shareable Link
Copy Link
paste it in new tab
Open Folder
***Notice everything is duplicated (because you are sharing with yourself)
Exit out of Shared Tab and close
From Center, Open same App again and disable it form Pop up Details
Try to Unbookmark it ( it shouldnt unbookmark)
Go back to Hud page
Verify this app does not display in folder
Go back to Center | Listing Management| My Listings
Open App
Enable it 
Go to HUD | Folder
RESULTS - App shows once not twice
EXPECTED RESULTS - Because everything duplicated that first time I expected to see all duplicates enabled again in the folder?

**Comment by akonsowski** [comment]
i just tried this and both the applications were there in the folder. can you try this again with me to make sure i am doing this right? @tdressel

**Comment by akonsowski** [comment]
if you only have one bookmark in the folder and duplicate it and follow these steps the folder will go away and when you re-enable the app it will only come back once.
