### ISSUE TITLE
Recent Activity - Deleted listings do not appear in list

### ISSUE THREAD

**Issue by stephanieerin** [ozone-development/ozp-center#87]

**Comment by mparizernc** [comment]
Why is this a bug? They never have once a listing is deleted all data associated with that listing in the system is removed.

**Comment by clarkjefcoat** [comment]
Also, the action of a listing being deleted does not appear in the Recent Activity page.  This is something the admins would like to track.

**Comment by stephanieerin** [comment]
When I looked into this it was deemed a bit of a back end effort to implement, we currently don't gather that information for deleted listings (and don't really have anywhere we would, change log items are attached to listings, a deleted listing takes it's change logs with it).

**Comment by tonyalletag** [comment]
If a listing is deleted it should show up as deleted and by who on the "Recent Activity" tab on the listing management page.

**Comment by tdressel** [comment]
Now displays "<username> deleted the listing."

**Comment by tdressel** [comment]
Passed on Staging.
