### ISSUE TITLE
Create/Edit Page - Tab transitions

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#92]
Adding an animation / transition when the tabs open and close.

**Comment by clarkjefcoat** [comment]
Is this OBE due to page redesign?  Is #155 the new version of this idea?

**Comment by rpokorny** [comment]
This ticket is simply for adding animations to the tab sections. So when a new section opens (whether from a click or from the behavior desired in #155), it slides open gracefully instead of instantaneously switching to the open state.

**Comment by sdeighan** [comment]
This is just an enhancement to make the tab-openings look nicer. The standard ones are too slow, increasing the time required and they look a little weird. The original developer thought that he could modify them to look nicer, but that it would require too much time to get it in before IOB. It is just a minor aesthetic improvement.

#155 is a feature that makes the tabs functional as a way for users to track where they are within the form and their progress through the form. It is asking for the tabs to reflect where the user is. For example, as the user finishes adding in the details, he moves to the "Resources" field. As he moves to the "Resources" field, the "Listing Details" tab closes and the "Resources" tab opens.
#155 is a more major effort and much more useful for the users.

**Comment by wski** [comment]
Due to the work required and performance issues that may occur (potentially the same as the animation issues with tooltips) we have decided to stick with the current implementation.
