### ISSUE TITLE
In IE9 hitting the enter button while focus is on the search field clears the search

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#94]
Steps to reproduce:
1. type search criteria in search field
2. hit enter

- Search criteria is cleared and all apps are returned.

**Comment by mparizernc** [comment]
@wski I tested your fix in IE9 and IE11 but the broken behavior is still happening.

**Comment by nishp1** [comment]
> since events are delegated, it won't work.

**Comment by mparizernc** [comment]
All browsers

verified that the behavior is now fixed.
